### ISSUE TITLE
Weird typerrors

### ISSUE THREAD

**Issue by themattchan** [elm-lang/elm-compiler#1004]
Don't know which repo to post this to, so I'll put this here:

centerAngle : Int -> Int -> Float
centerAngle n i = (pi * ((2 * i) - 1)) / (2 * n)

Type mismatch between the following types on line 14, column 20 to 48:
       Int
       Float
   It is related to the following expression:
       (pi * ((2 * i) - 1)) / (2 * n)

Why? [It works without the type signature.]

**Comment by jvoigtlaender** [comment]
Without the type signature, `n` and `i` are simply both inferred to be `Float`s, so that's why it works then.

With the type signature, you *insist* that `n` and `i` should be `Int`s, but then *use* them as if they were `Float`s (for example, by multiplying `pi` with something that gets its type from `i`). So that's why it doesn't work then.

You may want to use `toFloat` at some places.

**Comment by evancz** [comment]
Thanks for asking, this seems like a great candidate for https://github.com/evancz/error-message-catalog since I expect this to come up relatively frequently.

For some more info, Elm makes a distinction between floats and ints. It also does not do implicit conversions between these two types. It also will infer the type of `4` as `number` which can resolve to either `Int` or `Float` depending on usage. So while we can't automatically convert between these types in general, we can figure out what kind of *literal* you want.

Does that explanation help? Or @jvoigtlaender's? Let us know so we know whether we can close this issue :)

**Comment by themattchan** [comment]
Thanks @jvoigtlaender and @evancz! 

I thought Elm did numbers with typeclasses like Haskell --- this function was meant to compute an arithmetic sequence given two integers, e.g. `for (i <- [1..n]) {...}`. I guess I'll just relax the int requirement to number.

**Comment by evancz** [comment]
Maybe you want `(//)` instead of `(/)` then? The former is integer division and the later is floating point division, like in python.

**Comment by themattchan** [comment]
I do want floating point division; the result is meant to be in radians (represented as a float). Changing the type signature from Int to number works fine.
