### ISSUE TITLE
conflict between types message

### ISSUE THREAD

**Issue by flip111** [elm-lang/elm-compiler#1061]
```
The 1st argument to function `onClick` has an unexpected type.

86|                  onClick address (Sort x)
                             ^^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Signal.Address a

    List Attribute -> List Html -> Html
```

As a beginner i get confused with what is the current type and what is the expected type. Maybe instead of this text something like

```
86|                  onClick address (Sort x)
                             ^^^^^^^

The 1st argument to function `onClick` is of type

    List Attribute -> List Html -> Html

Instead expected:

    Signal.Address a
```
(i'm not entirely sure if i have them the right way around now while typing this)

**Comment by evancz** [comment]
This is a long requested addition. It is harder than it sounds for various reasons, but the point here is that we know lots of people want this and would like to add it. I'm going to close this as a known issue, and for future error message quality ideas, please report them as an issue on https://github.com/elm-lang/error-message-catalog which is all about this! I suspect there's an issue open about this idea in particular with a more complete explanation of why such a thing is not absolutely trivial to add.

**Comment by flip111** [comment]
The best related issue i could find is this one https://github.com/elm-lang/error-message-catalog/issues/3 which is not really the same i think. Intuitively i would say it would be really easy for the compiler to know which is the expected type and which is the found type. Anyway i don't know enough about this stuff so i'll leave it at this then ...

**Comment by flip111** [comment]
The website share-elm.com has a version of elm that can make the distinction between the actual type and the expected type ?!

See http://www.share-elm.com/sprout/560310aee4b0966c193dc36f

**Comment by Apanatshka** [comment]
yes, it used to be in the compiler. But the compiler didn't always give the expected/actual pair in the order that people considered intuitive. So it was removed to keep people from being confused.

**Comment by flip111** [comment]
@Apanatshka do you mean that it sometimes display first expected and then actual and other times first actual then expected?

**Comment by Apanatshka** [comment]
No, the flips the meaning of "expected" and "actual" sometimes. Your example is a good illustration:
**The second error is intuitive:** Expected is `String` because `toText` expects a `String` argument, but since you're calling `map` with two arguments, a list of something comes out (the actual type). 
**But the first error** says it expects `[a -> (number, a)]` but the actual type is `number -> a`. If I look at that code I'd say the *actual* type of `(map (,) [1,2])` is `[a -> (number, a)]`, whereas the outer `map` *expects* `number -> a` since the first argument has to be a function and the second argument is a list of `number`.

**Comment by flip111** [comment]
Uf ok i understand. I hope there are some possibilities to clear this up because for a beginner this is very difficult to track down yourself. Thanks for the explanation though! Do you know if there is something about this in the error-message-catalog?

**Comment by Apanatshka** [comment]
If I search the issues of error-message-catalog for "expected" or "actual" I cannot find any issues about it, so there probably isn't anything about this.

**Comment by evancz** [comment]
Be sure to search closed things as well. This issue is known from like 2+ years ago. I don't need an issue to remind me about it. The point of error message catalog is to document weird and unexpected things where having an example is valuable.

I know about this, so keeping issues open is more paperwork unless we can make sure every future person is likely to find that open issue.
