### ISSUE TITLE
Top-level function declarations using the lambda syntax

### ISSUE THREAD

**Issue by nikita-volkov** [elm-lang/elm-compiler#1073]
I propose to implement support for and promote the following syntax for top-level definitions:

```elm
sum : Int -> Int -> Int =
  \a b -> a + b
```

which is the same as

```elm
sum : Int -> Int -> Int
sum a b = a + b
```

Reasons:
* Solves the annoyance of having to type the name of the function twice. Removes one refactoring task as well.
* A single unified syntax for lambdas and top-level functions.
* Solution to the problem of beginners misperceiving them as different things, which they aren't.
* It's completely backward-compatible. This will allow to apply the promotion strategy of gradually introducing the new syntax into the docs and tutorials.

**Comment by mgold** [comment]
Elm syntax has generally followed the "there's exactly one way to do it" philosophy, because of your third bullet point: with this philosophy, things that look different, are different. One exception is that your second code block is really sugar for

```elm
sum : Int -> Int -> Int
sum = \a b -> a + b
```

But it's such a nice sugar that we keep is around. I agree rewriting function names is a bit of a pain, but one that can be solved by tooling (e.g. smartly generate `sum a b = ` after typing the annotation).

**Comment by gyzerok** [comment]
It may be simply solved by code-snippets

**Comment by evancz** [comment]
This is interesting, but I don't have any plans to do something like this soon.

There are a bunch of ideas for "task syntax" that may be nice with this, but it is a number of releases away and perhaps will never happen. So we'll consider it again at a more appropriate time.
