### ISSUE TITLE
Requesting more type realiasing in compiler messages

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1154]
This came up for me in elm-stylesheets, where error messages that make use of type aliases are actually quite nice, but the ones without them expose a lot of internal union type plumbing that makes for long and unpleasant error messages.

Here's a small example to reproduce:

```elm
type Thing a =
    Something a
    
type alias StringyThing =
    Thing String

type alias IntyThing =
    Thing Int

foo : IntyThing
foo =
    Something "foo"
```

Error message:

```
The type annotation for `foo` does not match its definition.

12| foo : IntyThing

The type annotation is saying:

    Thing Int

But I am inferring that the definition has this type:

    Thing String
```

The first part of the error message is incorrect; it reports that "the type annotation is saying: `Thing Int`" but this contradicts the code sample right above that, where we can clearly see that the type annotation is actually saying `IntyThing` instead.

It would be really nice if it noticed that there are type aliases for both alternatives and referenced them, like so:

```
The type annotation for `foo` does not match its definition.

12| foo : IntyThing

The type annotation is saying:

    IntyThing

But I am inferring that the definition has this type:

    StringyThing
```

**Comment by evancz** [comment]
Realiasing things is tricky business, so "fix this case" will break others.

You are saying "I want the compiler to look at all types and use type aliases if anything matches". This kind of works, but kind of not. If we did this blindly, every `Float` would display as `Time` for example.

In 0.16 I have tried to make type aliases "contagious" so if you use it once, it will spread from there. This means you get it if you ever called it that type, but otherwise it does not pollute things.

I am uncertain what is "the right thing to do" here.

**Comment by evancz** [comment]
Is it possible to show the actual error message you saw? It is hard to understand how you perceive the issue from this example.

**Comment by mgold** [comment]
I remember Standard ML does not do aliasing in its errors, so this is not a new problem. Not asking for anything soon, but some possible heuristics: re-alias only to types defined within the module, or imported exposed within the module, or that are "simpler" than the original type. By "simpler" I mean not a single word, so Time isn't simpler than Float, but an alias is simpler than a record or tuple.
