### ISSUE TITLE
Polymorphic functions

### ISSUE THREAD

**Issue by gyzerok** [elm-lang/elm-compiler#1185]
Mb I'm missing something, but it seems docs says nothing about this. Suppose I'm using `elm-html` and `elm-svg`. I cannot do it like this:

```elm
import Html exposing (..)
import Html.Attributes exposing (..)
import Svg exposing (..)
import Svg.Attributes exposing (..)

view =
  div [ class "foo" ]
    [ svg [ class "bar" ] []
    ]
```

As I can understand `class` is definitely the same for `Html` and `Svg` but compiler doesnt understand that and gives me error. Its very annoying to use it in a way `Html.Attributes.class` and `Svg.Attributes.class`. The same issue with `Html.svg` and `Svg.svg`. Maybe there is a common good looking solution for this?

**Comment by jvoigtlaender** [comment]
`Html.Attributes.class` and `Svg.Attributes.class` are really different functions.

They have different return types (`Html.Attribute` vs. `Svg.Attribute`) *and* different implementations. Namely, essentially:
```elm
Html.Attributes.class string = VirtualDom.property "className" (Json.string string)
```
vs.
```elm
Svg.Attributes.class string = VirtualDom.attribute "class" string
```
So, it's not the same function at all. It just has, minus the module qualifiers, the same name. Now, one might want to have overloading here, so that it becomes indeed calls to the "same" function in some sense. But that would require language features that Elm currently does not have.

**Comment by gyzerok** [comment]
@jvoigtlaender Thank you for clarifications. Here may be considered another example with adding `toString` method for custom type like I did in https://github.com/evancz/elm-html/pull/85 which cause probably the same problem.

May we somehow rename this and consider as a feature request?

**Comment by jvoigtlaender** [comment]
The feature request would be "Add type classes like in Haskell, or an equivalent language feature". I'm pretty sure that Evan doesn't need a reminder about this through a GitHub issue, since it has come up so often.

Generally, language design discussions like this are better suited (in the Elm community at least) for the [mailing list](https://groups.google.com/forum/#!forum/elm-discuss).

Concerning the "overloaded polymorphism" topic specifically, you might want to search that mailing list for the words "type class". Probably you will find many discussions that relate to your wishes expressed here and in https://github.com/evancz/elm-html/pull/85, and probably also some indication about why this is not something that is going to be added very soon on the language level.

**Comment by gyzerok** [comment]
@jvoigtlaender Would you think it has to be closed?

**Comment by jvoigtlaender** [comment]
Generally I know that Evan wants issues in the Elm repos to be "actionable" in some sense. So if there is nothing concrete that can be done about this here (apart from further discussion, which might better happen elsewhere), yes, I think it should be closed.
