### ISSUE TITLE
Not hot swapping TypeError: undefined is not an object (evaluating 'event.time')

### ISSUE THREAD

**Issue by tel** [elm-lang/elm-compiler#1202]
When running elm-reactor on a fresh Elm Platform install on OS X hot swapping does not occur (tested Chrome and Safari). Furthermore, when clicking the "refresh" icon I see errors like

```
Uncaught TypeError: Cannot read property 'time' of undefined
runtime.timer.now @ debug.js:12209
debugState.refreshScreen @ debug.js:12180
restart @ debug.js:11749
(anonymous function) @ debug.js:11629
notify @ debug.js:1225
node.notify @ debug.js:3377
broadcastToKids @ debug.js:3294
node.notify @ debug.js:3415
broadcastToKids @ debug.js:3294
node.notify @ debug.js:3317
notify @ Tut.elm?debug:1324
(anonymous function) @ debug.js:3341
```

The relevant line in `debug.js` looks like

``` javascript
	runtime.timer.now = function() {
		if (debugState.paused || debugState.swapInProgress)
		{
			var event = debugState.events[debugState.index];
			return event.time;
		}
		return Date.now() - debugState.totalTimeLost;
	};
```

**Comment by jvoigtlaender** [comment]
This seems an issue relevant for the https://github.com/elm-lang/elm-reactor repo, not the current one here.

Maybe you were wrongly pointed here due to [this problem](https://github.com/elm-lang/core/issues/430) (which mentions a by now non-existent repo in an error message, being redirected on GitHub to the current repo here).

In any case, please close the issue here and instead see whether you have something to add to these swapping-related issues in the appropriate repo: https://github.com/elm-lang/elm-reactor/milestones/Swapping.

**Comment by tel** [comment]
Will do. Thanks.

I think I'm just still getting used to the elm ecosystem broadly.
