### ISSUE TITLE
Relax type-checking of main: Allow for alternative virtual-dom implementations

### ISSUE THREAD

**Issue by ThomasWeiser** [elm-lang/elm-compiler#1225]
The compiler checks the type of `main` to be of either `Element` or `Html` or a signal thereof. These checks are hard-coded, see:

https://github.com/elm-lang/elm-compiler/blob/1b1a899212e7caa4de6ce2a454d9ce2ee8f2abbd/src/Nitpick/TopLevelTypes.hs#L48-L106

In this check the type `Html` has to be type `Node` from the module `VirtualDom` from the package `evancz/virtual-dom`.

Problem: You cannot easily swap virtual-dom with a modified version or an alternative implementation.

Admittedly, there are quirky workarounds with the current compiler:

-  Install evancz/elm-html and then modify the packages in `elm-stuff/packages/evancz/...` (or link to the modified packages)
- Cheat the compiler by faking your app's repository name in `elm-package.json` to be `https://github.com/evancz/virtual-dom.git`

A better solution would allow a package or a module to state that it exports a type acceptable for main.I have no idea about a good way to do this.

The runtime would also need to know how to render `main`'s output, at least if the native module is not named `VirtualDom`. That's currently also hard-coded:

https://github.com/elm-lang/core/blob/016d44a851fd3bcc4f5ffeef79431ac53add5e88/src/Native/Runtime.js#L312-L326

Related issue: [How to handle user-defined types that want to go through main?](https://github.com/elm-lang/elm-plans/issues/19)

**Comment by rtfeldman** [comment]
> Problem: You cannot easily swap virtual-dom with a modified version or an alternative implementation.

This seems like a feature, not a bug. :wink: 

Changing this policy would open the door to the fragmentation problems we see in the JS world, where newcomers are bombarded with conflicting information as to whether they should be using React, Angular, Ember, etc, and "flavor of the week burnout" starts to set in.

One of the most refreshing parts about coming to Elm from JS is that there's one really nice accepted way to organize your UI, and everyone just follows that and focuses on building awesome things.

Nothing is perfect, so I assume there are incremental improvements to be had over this Incredibly Nice Experience that we already have, but I can easily imagine the detriment of fragmentation outweighing whatever those incremental benefits might bring.

I vote we keep this good thing going. :smile:

**Comment by ThomasWeiser** [comment]
Thanks for your answer. No motivation to promote fragmentation here.

I just want to experiment with additional features in elm-html/virtual-dom. Think of an virtual-dom-extra package. Currently this needs the aforementioned hacks.

**Comment by evancz** [comment]
I am interested in allowing other renderers to exist (though I share @rtfeldman's reservations) but if this happens, it will not look exactly like this proposal. Point is, this is something I have on my own personal list of items to look into, so I'd rather continue tracking it there.

**Comment by roman** [comment]
I understand the argument of @rtfeldman, but this limits adoption considerably, in our particular case, all our `Component` APIs (company wide) are implemented using dumb React components. I was trying to come up with a `react-html` library + react-app, to ensure we use the same React Components in all apps of our company. This restriction shatters all possibilities of using Elm, I have two options, either fork the compiler (which is something I'm not interested at all in doing) or somehow transform a React component into a `Graphics.Element` which, I think is not possible, because React's API doesn't provide `diff` / `patch` family of functions.

Please I beg you to consider React as part of your supported `html` outputs, I'm certain this library is not a "flavor of the week burnout", the number of stars on React surpasses at this point the ones that jQuery has.

I would be happy with a "partially working/limited" React support... at least something to get us started.
