### ISSUE TITLE
Feature Request: Existential Types 

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-compiler#1248]
So I've run into a case where I wish to expose an interface dependent on the presence of a typed field on a record. For example

```elm
type alias Foo = 
  { x : Int 
  }

type alias Bar = 
  { x : Int 
  , y : Int 
  }
```

So its possible to define a function the relies on the presence of `x : Int` and will work with either `Foo` or `Bar`. 

```elm 
xPlus : { a | x : Int } -> Int -> Int
xPlus {x}  i = x + i

foo : Foo
foo = 
  { x = 3 
  }

bar : Bar 
bar = 
  { x = 4
  , y = 6
  }

xPlus foo -- will compile 
xPlus bar -- will compile
``` 

So I think that `Foo` and `Bar` are subsets of `{ a | x : Int }`, which makes this feel inconsistent:

```elm
-- wont compile, suggests `Foo a`
type alias Foo =
   { a | x : Int }

foo : Foo
foo = 
  { x = 3
  }
```

and of course 

```elm
type alias Foo a =
   { a | x : Int }

-- wont compile
foo : Foo a
foo = 
  { x = 3
  }
```

so `xPlus` cannot have a type like `xPlus : Fooable -> Int -> Int` which I feel is cleaner overall than `xPlus : { a | x : Int } -> Int -> Int` and still handle both `Foo` and `Bar` records. Particularly in cases where field names get long, and the function is interested in more than one.

So I'd like to propose allowing aliases like 

```elm
type alias Foo =
   { a | x : Int }

foo : Foo
foo = 
  { x = 3
  }

{-| should not compile
bar : Foo 
bar = 
  { x = 4
  , y = 6
  }
-}

bar : Bar 
bar = 
  { x = 4
  , y = 6
  }

xPlus : Foo -> Int -> Int
xPlus {x}  i = x + i

xPlus foo -- compiles 
xplus bar -- compiles
```

I think this kind of thing is possible in Haskell (not to say thats why I'm proposing it), but it should be doable.

**Comment by jvoigtlaender** [comment]
This works:
```elm
type alias Fooable a = { a | x : Int }

type alias Foo = Fooable {}

type alias Bar = Fooable { y : Int }

foo : Foo
foo = 
  { x = 3
  }

bar : Bar 
bar = 
  { x = 4
  , y = 6
  }

xPlus : Fooable a -> Int -> Int
xPlus {x}  i = x + i

test1 = xPlus foo -- compiles 
test2 = xPlus bar -- compiles
```
Why is this not good enough?

**Comment by Fresheyeball** [comment]
I don't see a need for the separation between `Foo` and `Fooable`, nor do I see a value in the presence of `a` in `xPlus : Fooable a -> Int -> Int`. The whole point is to have the ability to truly alias something like `{ a | x : Int }` which seems to really be `forall a. { a | x : Int }`.

**Comment by jvoigtlaender** [comment]
You haven't really said what is wrong with the solution I suggested. You originally seemed to say that you wanted to be able to pass
```elm
foo : Foo
foo = 
  { x = 3 
  }
```
and
```elm
bar : Bar 
bar = 
  { x = 4
  , y = 6
  }
```
to a function
```elm
xPlus : ... -> Int -> Int
xPlus {x}  i = x + i
```
and use a type alias instead of the `...`.

The definition
```elm
type alias Fooable a = { a | x : Int }
```
allows you to do that.

If you don't like the `a` parameter there, you will need a new language feature.

In particular:
* No, `Foo` and `Fooable` are too different (they even have different *kinds*) to be unifiable in an ML-style type system.
* No, that's not `forall`-polymorphism. It's `exists`-polymorphism. The type you seek is `exists a. { a | x : Int }`. Existential type polymorphism is not supported by Elm, but has been discussed several times (on the mailing list and probably in some issues in this repository here as well).

**Comment by jvoigtlaender** [comment]
I guess [this message/thread](https://groups.google.com/d/msg/elm-discuss/R9TonevDCqA/KagVtVAkCgAJ) might be interesting to you. Probably the most recent discussion of existential types on the mailing list.

**Comment by Fresheyeball** [comment]
ok, I'll hope over there. But yes, I am proposing a new language feature.

**Comment by jvoigtlaender** [comment]
Maybe change the issue title to something like "Feature request: existential types"?

**Comment by Fresheyeball** [comment]
Done. Also, thanks for clarifying. I wasn't sure what kind of types I was requesting.

**Comment by jvoigtlaender** [comment]
BTW, maybe this should be added to the meta-issue about type system extensions: https://github.com/elm-lang/elm-compiler/issues/1039. Ask Evan?

**Comment by tonymorris** [comment]
This problem is solved by exploiting a Twan van Laarhoven encoding of lenses and subsequent work by others to find encodings of similar structures, which all generalise to what has been called an `Optic`. The union type given (`Fooable`) can further exploit this work with a specialisation of `Optic` called a `Prism`.

Unfortunately, it is not possible to encode any of this with elm and is likely to stay that way (see #1039). Any demonstration of this work would require Haskell or similarly utilisable type system.

**Comment by evancz** [comment]
I'd say this is covered by #1039, so I am going to close in favor of the meta issue.

**Comment by brainrape** [comment]
I found a clunky way to simulate existential types by wrapping the type parameter of a polymorphic type in an unexported type.  The result is, you can only write polymorphic functions over the polymorphic type. If you try to write a function where you specify the type variable, it either won't compile, or you can never call it.
https://github.com/brainrape/elm-existential
