### ISSUE TITLE
Re-export causes runtime error

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-compiler#1255]
```elm
module Foo where 

foo : Int
foo = 34
```

```elm
module Bar where 

import Foo exposing (foo)

foo : Int 
foo = foo
```

```elm
module Main where 

import Bar exposing (foo)
import Graphics.Element exposing (Element, show)

main : Element 
main = show (foo + 1)
```

Will be `NaN` as `foo` is `undefined` and in JavaScript `undefined + 1 == NaN`. However in other cases this will create runtime errors.

**Comment by jvoigtlaender** [comment]
I think that when you write `foo = foo` there, you are not saying
```elm
Bar.foo = Foo.foo
```
Instead, you are saying
```elm
Bar.foo = Bar.foo
```
So this is then just ticket https://github.com/elm-lang/elm-compiler/issues/873#issuecomment-168686792, it has nothing to do with re-exporting, and does not need a new ticket.

If you do want to re-export rather than define a self-recursive value/loop, you should be able to write
```elm
module Bar where 

import Foo exposing (foo)

foo : Int 
foo = Foo.foo
```

**Comment by Fresheyeball** [comment]
Fair enough, I was not aware of #873
