### ISSUE TITLE
Preventing cascading type errors can be overly aggressive

### ISSUE THREAD

**Issue by FPtje** [elm-lang/elm-compiler#1276]
Let's first look at a concrete example of the issue. Let this be a full Main.elm file.

```elm
import Html

main : Html.Html
main = Html.text "asdf"

horses = True == "asfd"
apples = True == "asfd"
```
Two separate bindings with very clear type errors, yet only one error is thrown (only the relevant part of the error is copied):

```
The right argument of (==) is causing a type mismatch.

14▒          True == "asfd"
```

`apples` errors, but `horses` doesn't. But they're two separate bindings. 

Here's a counterexample:

```elm
type A = A
type B = B

horses = True == "asfd"
chickens = A == B
```
Now two errors are given. One for `horses` and one for `chickens`.

# Cause

The problem lies with the `Error` constructor from `Type.Type`. The `Type.Unify.unify` function calls `mergeHelp expected actual Error` when the type inferencer hits two incompatible types. That changes the `UF.Point`s of the Union-Find stuff to basically make this:

![](https://dl2.pushbulletusercontent.com/0VIlxchHVEvW11R8L1TbgzE1XLYqFVtu/Thesis%20-%20Page%2012.png)

The type variables of both the Bool constant and the String constant conceptually get a parent in the Union-Find structure that contains Error. **However**, because of the implementation of `UF.union'`, the String constant gets the Bool constant as parent, and the Bool constant has its type variable's `_content` is replaced with `Error`. Which means:

Everything that has anything to do with Bool will now type check. After all, all unifications with `Error` succeed.

To show the point, if you add Show instances to literally every data structure in `elm-compiler` and `Debug.trace` the top type constraint after solving the above example, not only do you get a huge output, but this will be part of it:

```
("Basics.&&",Annotated (TermN (Fun1 (VarN UnionFindThing: Descriptor {
    _content = Error
    ,_rank = -1,_mark = 8,_copy = Nothing
}
) (TermN (Fun1 (VarN UnionFindThing: Descriptor {
    _content = Error
    ,_rank = -1,_mark = 8,_copy = Nothing
}
) (VarN UnionFindThing: Descriptor {
    _content = Error
    ,_rank = -1,_mark = 8,_copy = Nothing
}
))))))
```

Basically it says the type of `Basics.&&` is `Error -> Error -> Error`. In the meantime, String related stuff remains normal:
```
("Debug.crash",Annotated (TermN (Fun1 (VarN UnionFindThing Descriptor {
	_content = Atom (Canonical {
		home = BuiltIn,name = "String"
	}
	),_rank = -1,_mark = 0,_copy = Nothing
}
) (VarN UnionFindThing Descriptor {
	_content = Var Rigid Nothing Nothing,_rank = -1,_mark = 3,_copy = Nothing
}
))))
```
which basically says that the type of `Debug.crash` is still `String -> typeVariable`.

# Conclusion 
Preventing cascading type error messages is a noble cause, but this solution kind of overshoots its purpose. Perhaps making a fresh `UF.Point` type variable and merging them both to that solves this issue while still preventing cascading type error messages. I haven't tried that yet.

**Comment by evancz** [comment]
This is definitely somewhat weird, but knowing the implementation, I don't think there is an alternative.

In unification, you start unifying structures, and only bail if it is not safe to unify any further. So if you have two results `Result String Int` and `Result String Float` they will unify safely to `Result String a` and *then* fail.

Now, you might say, the right thing to do is `Result String X` and put the error in the spot where unification actually failed. Well, that may be where the type error is, but the actual error could be more complex than that and it should be just an `Int` but some code was forgotten. The compiler cannot know that.

So I think it makes sense to err on the side of caution with cascading error messages. As is, the error messages you get will *always* be due to a real problem in the most specific place possible. On top of that, I think it's actually fine to get fewer type errors that are more focused, so I'm not certain more cascading would even be nice. Gotta fix the root things anyway.

**Comment by mgold** [comment]
I love it when Evan gives detailed explanations about compiler things!
