### ISSUE TITLE
Show a compilation error if a top-level value redefined a value exposed from a module

### ISSUE THREAD

**Issue by kossnocorp** [elm-lang/elm-compiler#1303]
[It's me again](https://github.com/elm-lang/elm-compiler/issues/1302) :neckbeard:.

It's not possible to redefine top-level values, and this is great!

```elm
qwe = 123
qwe = 456
```

...gives:

```
Naming multiple top-level values `qwe` makes things ambiguous. When you say
`qwe` which one do you want?
```

However, when I redefine a value exposed from a module, Elm is cool about that. And this is not cool:

```elm
import Html.Attributes exposing (..)
id = 123
```

...gives:

```
Success! Compiled 1 modules.
Successfully generated bingo.js
```

I expect something like:

```
Naming multiple top-level values `id` makes things ambiguous. When you say
`id` which one do you want?
```

**Comment by evancz** [comment]
This is a deliberate choice. The idea being that if you define something locally, it takes precedence over anything else. Same choice is made in languages like Haskell, Julia (I believe), and probably a ton of others. Reopen an issue if you can find any languages that are a counter-example.

Generally speaking, you should not be using open imports with `exposing (..)` because it leads to frail code. This is what [the style guide](http://elm-lang.org/docs/style-guide) says, and it's generally how folks will do things in production quality code-bases.

**Comment by kossnocorp** [comment]
@evancz I see, thank you, for clarification.

[The course](https://pragmaticstudio.com/elm) (cc @clarkware) claims that this is preferable way to avoid verboseness of HTML constructions (and it makes sense to me):

```elm
pageHeader =
  Html.h1 [ Html.Attributes.id "logo", Html.Attributes.class "classy" ]
    [ title "Bingo" 3 ]
```

vs

```elm
pageHeader =
  h1 [ id "logo", class "classy" ]
    [ title "Bingo" 3 ]
```

**Comment by mgold** [comment]
Right, so do `import Html.Attributes exposing (h1, id, class, title)`.
