### ISSUE TITLE
Where lack of constructors for extensible records is hurting

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1308]
@evancz said in https://github.com/elm-lang/elm-compiler/issues/1283#issuecomment-183515916 to open a new issue if there is a valid use case of having (at least some limited way of) record extension in expression syntax.

Consider the case of writing `Json` decoders in the presence of extensible records. For example, let be given the following type definitions:
```elm
type alias A = { a1 : Int, a2 : Float }
type alias B a = { a | b1 : String, b2 : Bool }
```
and assume we want a decoder for `B A`.
In Elm 0.15, one could have written the decoder as follows:
```elm
apply = object2 (<|)      

dec : Decoder (B A)
dec = B `map` ("b1" := string)
      `apply` ("b2" := bool)        
      `apply` (A `map` ("a1" := int)
               `apply` ("a2" := float))
```
In Elm 0.16, this does not work, because the constructor `B` used in the first line of `dec` does not exist. Instead, one has to write:
```elm
makeBfromA : String -> Bool -> A -> B A
makeBfromA b1 b2 { a1, a2 } = { a1 = a1, a2 = a2, b1 = b1, b2 = b2 }

dec : Decoder (B A)
dec = makeBfromA `map` ("b1" := string)
      ...
```
Having to implement and use this `makeBfromA` function is bad.

1. Imagine that there are not just `a1` and `a2` in the `A` definition and `b1` and `b2` in the `B` definition, but instead 7 fields in `A` and 8 fields in `B`.
2. Moreover, imagine that the program/definitions later get refactored, for example by adding or removing fields in either of the two record definitions. That will now always require changes to the `makeBfromA` function, whereas previously no such need would have arisen (since in Elm 0.15 one wouldn't have to write the `makeBfromA` function in the first place).
3. Also, imagine that we need a decoder for `B C` (for yet another record type `C`), either additionally or instead of the decoder for `B A`. Unlike in Elm 0.15, it will not be enough to change the `(A ...)` part in the definition of `dec` into something of the form `(C ...)`. Instead, we will also have to replace `makeBfromA` by `makeBfromC` (and implement this additional `makeBfromC` function).

So I'm wondering: Does this count as a "valid use case" in the sense of the comment pointed to above? If not, what is the "defense" for having to implement and maintain the `makeBfromA`/`makeBfromC` functions? Or is there another solution to the above issues that does not involve bringing constructors for extensible records back into Elm? How would you advise to write `dec` (and keep it maintainable under refactorings as sketched above)?

EDIT: Expanded and clarified.

**Comment by jvoigtlaender** [comment]
In a related thread on the mailing list, Evan [suggested](https://groups.google.com/d/msg/elm-discuss/AaL8iLjhEdU/pBe29vQdCgAJ) that record nesting is always better than record extension. Maybe that is the case, it seems reminiscient of the "aggregation is better than inheritance" argument in OOP. For the specific example above, it would mean that one shouldn't have started by defining
```elm
type alias A = { a1 : Int, a2 : Float }
type alias B a = { a | b1 : String, b2 : Bool }
```
and then tried to work with type `B A`, but instead should have defined:
```elm
type alias A = { a1 : Int, a2 : Float }
type alias B_A = { b1 : String, b2 : Bool, a : A }
```
and could then have written:
```elm
dec : Decoder B_A
dec = B_A `map` ("b1" := string)
        `apply` ("b2" := bool)        
        `apply` (A `map` ("a1" := int)
                 `apply` ("a2" := float))
```
Fine.

Two considerations on top of that:
* The scenario from the 3. point in my previous comment would still be a bit cumbersome, because one would have to inroduce/use `B_C` instead of reusing `B`. But maybe that's not a real concern, because one shouldn't *want* to use `B C` (in light of the general "nesting is better than extension" hypothesis).
* If record nesting is better than record extension, why are programmers tempted into using record extension by availability of the syntax `type alias B a = { a | b1 : String, b2 : Bool }` in the first place? Maybe it should go.

Also, an alternative consideration:
* What about re-introducing constructors for extensible records, but no other means for record extension in expression syntax? If I remember the discussion about removing record extension expression syntax correctly, the reasoning had to do with confusing errors when people mixed up `=` and `<-` (record extension vs. record update). That is not an argument against record constructors, though. Was there actually a bad case in Elm 0.15 concerning the extensible record feature that had to do with *constructors*? If not, did they absolutely have to be removed along with the other syntactic features?

**Comment by mgold** [comment]
Let me try to fame this with something closer to a real-world example, a game. (I'm thinking out loud, please bear with me.)

``` elm
type alias Named a = { a | name : String }
type alias HitPoints a = { a | hp : Int }
type alias Positioned a = { a | x : Float, y : Float }
type alias Moving a = Positioned {a | dx : Float, dy : Float }

type alias StationaryEnemy = Positioned (HitPoints {})
type alias Enemy = Moving (HitPoints {})
type alias Player = Named (Moving (HitPoints {}))

isAlive : { a | hp : Int } -> Bool
isAlive {hp} =
  hp > 0
```

All of this is valid 0.16 Elm. Records built with this pattern can get very large, resembling large OOP classes, but at least there are no nested records. I see a few reasons why large, flat records might be better than aggregated, nested records. We can already write functions like `isAlive` which ignore most of the record. A value like `{ named : { name : String}, hitPoints : { hp : Int} }` looks really silly. (This is more true when the nested records are small; for large records it can make sense to nest rather than extend.)

Finally, working with nested record (especially writes) is very tedious, 

```elm
isAlive' : {a | hitPoints : { hp : Int } } -> Bool
isAlive' { hitPoints } =
  hitPoints.hp > 0

drinkHealingPotion' : Int -> {a | hitPoints : { hp : Int } } -> {a | hitPoints : { hp : Int } }
drinkHealingPotion' healBy record =
  let
     hitPoints = record.hitPoints
     newHitPoints =
        { hitPoints | hp = hitPoints.hp + healBy }
  in
    { record | hitPoints = newHitPoints }
```

For flat records, it's just
```elm
drinkHealingPotion : Int -> {a | hp : Int }  -> {a | hp : Int }
drinkHealingPotion healBy record =
  { record | hp = record.hp + healBy }
```

So, hopefully this isn't too far off-topic from extensible record type constructors. I'm trying to show that extensible record *types* are useful (as confirmed by their continued presence in the language). That is, the above code is evidence **against** what Janis calls the "'nesting is better than extension' hypothesis".

I think at this junction I've concluded that
* If you want to use nested records, allowing arbitrary expressions in `{ ... |` will be very helpful.
* If you want to use flat records, record constructors might be very helpful.

So far, all code is valid Elm but I haven't defined any values (terms) of these flat record types. Setting aside JSON decoding for a moment, if you want to define a `Player`, you have to do

```elm
player : Player
player =
  { name = "King Arthur", x = 0, y = 0, dx = 0, dy = 0, hp = 100 }
```

The following is *not* valid Elm 0.16:
```elm
player' : Player
player' = 
  Named "King Arthur"
  |> Moving 0 0 0 0
  |> HitPoints 100
  -- you might need |> {} at the end
```

So the question before us is, are the record constructors useful enough to add the complexity to the language?

... and for all of that, I'm really not sure. (Please pardon the long rambling post.)

**Comment by durkiewicz** [comment]
Nesting is sometimes worse than extension. We have an example in our current project. We're building a client application for an existing backend (which we cannot change). The backend returns large and nested documents (dozens of fields on each level) for GET requests and accepts documents of the same structure in POST requests when you want to do an update. In such case, the client application need to use the same document structure, otherwise it would be really confusing and error-prone at request construction level.

**Comment by jvoigtlaender** [comment]
@durkiewicz, maybe add this to the thread on the mailing list?

https://groups.google.com/forum/#!msg/elm-discuss/AaL8iLjhEdU/pBe29vQdCgAJ

**Comment by evancz** [comment]
I understand the core point here. I don't think it makes sense to track this on the compiler repo though, just makes it harder to see bugs, so I am going to close.

**Comment by RobertFischer** [comment]
Where did this conversation move to? I just ran into this issue and posted on Stack Overflow: https://stackoverflow.com/questions/47321406/extensible-records-and-higher-order-functions/47331413

**Comment by evancz** [comment]
There are no plans to add this back right now.
