### ISSUE TITLE
invalid syntax results in invalid type error

### ISSUE THREAD

**Issue by stiller** [elm-lang/elm-compiler#1318]
On the advice of @jvoigtlaender I am referring to this issue here:
https://github.com/elm-lang/error-message-catalog/issues/98#issuecomment-197228854
Since it appears to be a compiler bug and not an unclear error message.

**Comment by jvoigtlaender** [comment]
And here is an SSCCE:
```elm
f x = x.Counter

main = f { }
```
This results in error message:
```
Function `f` is expecting the argument to be:

    { b | Counter : ... }

But it is:

    {}
```
So the compiler is printing out a "type" `{ b | Counter : ... }` as if it were valid Elm, though it isn't.

**Comment by mgold** [comment]
So... should it print `{ b | Counter : a }` instead?

**Comment by jvoigtlaender** [comment]
@mgold, is your question serious? Have you read the context of this? Do you know that what you typed isn't a valid Elm type either?

**Comment by mgold** [comment]
No, I had not read the other issue. I thought the point of an SSCCE was that it didn't require digging into prior discussion?

`f x = x.Counter` ought to be an SSCCE on its own. No confusion about whether the field is present or not, just focusing on the capitalization.

**Comment by jvoigtlaender** [comment]
You didn't need to read the other issue or previous discussion. But maybe reading the title of the issue you are commenting on is not too much to expect? The title is "invalid syntax ...", my SSCCE is only two lines and less than thirty characters, so maybe it would have made sense on your part to look for *invalid syntax* in those two lines?

But of course you are welcome to propose a better SSCCE. Note that `f x = x.Counter` on its own is not an SSCCE, because it does not trigger the bug (printing out a non-type as a type) that the original poster was observing.

**Comment by mgold** [comment]
The "printing out a non-type as a type" is not the root cause. The root cause its that `f x = x.Counter` is accepted by the compiler. If it wasn't, it would never try to print a non-type as a type.

**Comment by jvoigtlaender** [comment]
And? Propose to rename this issue, or check whether there is already one for that cause, so that this one becomes superfluous and can be closed. Doesn't change the fact that the above was about the error message that was encountered, and that what I was giving was aiming to be an SSCCE for that issue.

**Comment by evancz** [comment]
Thanks for getting this reported @stiller! @avh4 and I are working on cleaning up the process here, so we made an "authoritative" issue for this at #1319.
