### ISSUE TITLE
Compiler errors change background color in PowerShell

### ISSUE THREAD

**Issue by CoderDennis** [elm-lang/elm-compiler#1334]
When running `elm make` from within PowerShell on Windows, any time there is a compiler error, the text background is changed from blue to black. This does not happen within the repl.

After that change to black, there is a mix between blue and black text backgrounds that looks really ugly.

It would be nice if the background color was left alone.

![image](https://cloud.githubusercontent.com/assets/409009/14139805/e7953b84-f63a-11e5-8f25-8754da62000a.png)

**Comment by jvoigtlaender** [comment]
In all likelyhood not an issue of the Elm compiler, but rather of https://github.com/ekmett/ansi-wl-pprint or of https://github.com/feuerbach/ansi-terminal or of it not being possible to completely simulate ANSI code behavior for Powershell (which would be something people at https://github.com/feuerbach/ansi-terminal would know or probably be interested to know, if you can make a minimal example independent of the Elm compiler).

**Comment by CoderDennis** [comment]
I'll check into those libraries. Success and other messages from elm don't change the background. Only compiler errors do this.

**Comment by jvoigtlaender** [comment]
@CoderDennis, I don't know for certain that the "fault" is in one of the libraries. But I know the lines that print out that piece you are showing there. It's [these](https://github.com/elm-lang/elm-compiler/blob/32e172986beec90eece9cd4d8d5088bc895c165f/src/Reporting/Report.hs#L61-L70) and [these](https://github.com/elm-lang/elm-compiler/blob/32e172986beec90eece9cd4d8d5088bc895c165f/src/Reporting/Report.hs#L73-L80). The `dullcyan` call is changing the foreground color of the "-- TYPE MISMATCH --- ..." line to dull cyan. There isn't any change to the background color. Neither have I seen such a switch to the background color in the code that generates the `preHint` that is output after the `messageBar`. But the `<>` operator between them, which comes from https://github.com/ekmett/ansi-wl-pprint, is responsible for making sure the dull cyan color is *only* used for the `messageBar`, not also for subsequent text. So that's where my hunch comes from that that library might be responsible. Maybe instead of only resetting the foreground color after dull cyan is not needed anymore, it also resets the background color (to default black). But I don't have proof.

Looking at [these](https://github.com/ekmett/ansi-wl-pprint/blob/master/Text/PrettyPrint/ANSI/Leijen.hs#L1221-L1228) and [these](https://github.com/ekmett/ansi-wl-pprint/blob/master/Text/PrettyPrint/ANSI/Leijen.hs#L1262-L1264) comments in the source code of that library at least suggests that remembering style state and restoring it at an appropriate point to the appropriate settings might not be implemented completely reliable there.

**Comment by evancz** [comment]
I agree with @jvoigtlaender's assessment on this one. We are relying entirely on other libraries to do the console colors. No trickiness lives in the compiler as far as I know.
