### ISSUE TITLE
Tuple type annotation missing parentheses

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1337]
To reproduce, put this in elm-repl 0.16:

```
> uncurry << fst
<function> : ( a -> b -> c, d ) -> ( a, b ) -> c
```

The correct type annotation would have parentheses around `c, d` like so:

```
> uncurry << fst
<function> : ( a -> b -> ( c, d ) ) -> ( a, b ) -> c
```

**Comment by jvoigtlaender** [comment]
No. The type that is shown is the correct type of that function. It takes a pair, of which the first component is a curried function (a -> b -> c), which is then returned in uncurried form.

**Comment by rtfeldman** [comment]
> It takes a pair
The function in question does not take a pair. Are you sure you're looking at the right part of the output? 😃

**Comment by rgrempel** [comment]
I think that jvoigtlaender's point is that the function you describe first applies 'fst'. So, it must take a Tuple. The second part of the Tuple is then thrown away -- that is the d. The first part is then uncurried -- that is the a -> b -> c. So, the signature output by elm-repl seems correct.

**Comment by rtfeldman** [comment]
Just to clarify: I'm not disagreeing with the type. I think the type is correct as printed.

I also think tuples in Elm always have parentheses around them. Is there disagreement on this point? Because a lack of parentheses is all I'm reporting here.

**Comment by rgrempel** [comment]
But there are parentheses! 

The first part of the Tuple is a -> b -> c. The second part of the Tuple is d. There is a comma between the first and second part. There is an opening parenthesis before the first part. There is a closing parenthesis after the second part. Looks like a Tuple. 

Perhaps you are seeing the first parenthesis as a grouping construct, rather than starting a Tuple?  Though I suppose it amounts to the same thing, if you see the comma as an operator.

**Comment by rtfeldman** [comment]
Ahh, I see your point. The intended grouping is `( (a -> b -> c), d ) -> ( a, b ) -> c`, not the second thing I wrote above.

I think this would be clearer, but it's clearly not a bug. I'll file a new issue as a suggestion.

**Comment by rtfeldman** [comment]
Closed in favor of https://github.com/elm-lang/error-message-catalog/issues/108
