### ISSUE TITLE
xss from defining things

### ISSUE THREAD

**Issue by awesomo4000** [elm-lang/elm-compiler#1348]
Compile and view this module in your browser. You should get a popup.

----
    module Test where

    f1 = "\';alert(String.fromCharCode(88,83,83))//';alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//\";alert(String.fromCharCode(88,83,83))//--></SCRIPT>\">'><SCRIPT>alert(String.fromCharCode(88,83,83))</SCRIPT>"

    f2 = "</script><script>alert(String.fromCharCode(88,83,83))</script>"

**Comment by rtfeldman** [comment]
To elaborate, based on my understanding, this only works when generating `index.html`, and would have no effect if you're compiling to a `.js` file.

The exploit is that if an attacker includes the string `</script>` in a string literal, then `</script>` will get emitted into `index.html`, and the browser will read it as the end of the in-progress `<script>` tag, oblivious to the fact that the `</script>` appears in the middle of a JS literal. From there the attacker can add another `<script>...malicious stuff goes here</script>` and go from there.

[OWASP suggests this is not preventable](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.230_-_Never_Insert_Untrusted_Data_Except_in_Allowed_Locations).

Based on this, I think a reasonable resolution to this issue is to disclaim somewhere that using the generated `index.html` is good for getting started quickly, but not safe for production use. (Not that it's terribly appealing for production use in the first place, but a caution seems reasonable all the same.)

<img width="849" alt="screen shot 2016-04-27 at 9 28 21 pm" src="https://cloud.githubusercontent.com/assets/1094080/14875414/6dd24012-0cbf-11e6-8939-6fdc49772746.png">

**Comment by mgold** [comment]
> disclaim somewhere

How about a warning generated if `script>` is found in the source code, among other places?

**Comment by rtfeldman** [comment]
I think it's pretty much all-or-nothing. Attempting to detect xss intent is an arms race that overwhelmingly favors attackers thanks to obfuscation.

If the vulnerability can't be fixed, best to make users aware of it when using this feature.

**Comment by rtfeldman** [comment]
An alternative would be to generate both `index.html` and `elm.js` when using the "generate the HTML for me" feature.

This would have the added side benefit of leaving you with something you could build on; currently when you want to (for example) add a CSS file, the generated `index.html` becomes useless and you chuck it. If instead it were importing `elm.js`, you could actually keep it and build on it.

**Comment by mgold** [comment]
I like the idea of generating `elm.js` and `index.html` by default.

**Comment by evancz** [comment]
Based on @rtfeldman's comments, I don't think we should track this here.
