### ISSUE TITLE
Error message contains strange characters after line numbers

### ISSUE THREAD

**Issue by emtenet** [elm-lang/elm-compiler#1363]
This happens on Windows 10 (Pro 64-bit and Home 32-bit) using 0.17-rc2 in a Command Prompt (cmd.exe) or PowerShell

This did not happen with 0.16 on the same systems.

Sample output from 0.17-rc2 on Windows 10 Pro 64-bit
```
d:\Source\Elm\Wired>"c:\Program Files (x86)\Elm Platform\master\bin\elm-make.exe" src\Error.elm
-- SYNTAX PROBLEM ------------------------------------------------ src\Error.elm


I ran into something unexpected when parsing your code!

3Ôöé type Error = invalid
                ^
I am looking for one of the following things:

    a constructor for a union type
    whitespace

Detected errors in 1 module.
```

The strange characters `Ôöé` are always the same for different errors or when an error displays multiple source lines.

Sample output from 0.16 on the same system
```
d:\Source\Elm\Wired>"c:\Program Files (x86)\Elm Platform\0.16\bin\elm-make.exe" src\Error.elm
-- SYNTAX PROBLEM --------- elm-stuff\packages\elm-lang\core\4.0.0\src\Array.elm


I ran into something unexpected when parsing your code!

1│ module Array exposing
                ^
I am looking for one of the following things:

    a listing of values and types to expose, like (..)
    reserved word `where`
    whitespace
```

**Comment by jvoigtlaender** [comment]
That happens because the symbol in question is not available in the utf8 code page on Windows. It probably shouldn't be used at all. The reason why it is different between Elm 0.16 and Elm 0.17 is that on Elm 0.16 the compiler (or `elm-make`) didn't automatically switch to the utf8 code page. So in Elm 0.16 the situation was:

* If you don't switch the code page yourself, you do get to see the nice symbol there, but you can have massive problems like https://github.com/elm-lang/elm-make/issues/33 and https://github.com/elm-lang/elm-make/issues/40.
* If you do switch the code page yourself, by first calling `chcp 65001` in the shell before doing any Elm stuff, those problems are solved, but you also get to see the strange symbol in the error message that you are now seeing with Elm 0.17.

In contrast, the situation with Elm 0.17 is that the equivalent of `chcp 65001` is done by Elm itself, so you always are in the second of the two situations above.

**Comment by jvoigtlaender** [comment]
Note: This is not the only case where those special symbols cause problems. One was reported quite a while ago: https://github.com/elm-lang/elm-make/issues/82. There, also, the output looks ugly in some situations (on http://elm-lang.org/try, and with Elm 0.16 on Windows if one does `chcp 65001`, which one has to do sometimes to avoid the other linked problems that cause the executable to completely fail).
