### ISSUE TITLE
Elm completeness check erroneously requests duplicate branch

### ISSUE THREAD

**Issue by z5h** [elm-lang/elm-compiler#1464]
Although all `Expression` cases have been accounted for, Elm commplains that Op A needs to be accounted for.

```Elm
type Op = A | B | C
type Expression = Expression Op Int

do : Expression -> Int
do expr =
  case expr of
    Expression A i ->
      i
    Expression op i ->
      let
        x = i * 2
      in
        case op of
          B ->
            x + 3
          C ->
            x + 4
```

**Comment by jvoigtlaender** [comment]
Yours is not a minimal example. The following one also has the property you are concerned about:
```elm
type Op = A | B | C
type Expression = Expression Op Int

do : Expression -> Int
do expr =
  case expr of
    Expression A i ->
      i
    Expression op i ->
        case op of
          B ->
            i * 2 + 3
          C ->
            i * 2 + 4
```
-------------

My analyis:

The error message the compiler gives is correct (both in your and in the reduced example). It says that the inner `case` does not have branches for all possibilities.

You will likely object that the possibility `A` is not possible because it is "handled" by a previous branch of the outer `case`. But that's not how the analysis works. Each `case` is looked at independently.

I don't know of any compiler doing exhaustiveness checks that would handle such "holistic analysis including all context". Likely it's not even doable in general. (Mumbles "Rice's theorem" under his breath.)

**Comment by z5h** [comment]
I'll preface this by saying I'm really not too fussy about this, and happy to accommodate the compiler by rearranging my code.

Having said that,
neither example has conditional branching that would affect the reachability of any of the `case` statements.
For that reason I viewed this as an error.

I might have expected the compiler to fail on the following code.

```Elm
type Op = A | B | C
type Expression = Expression Op Int
 
do : Expression -> Int
do expr =
  case expr of
    Expression A i ->
      i
    Expression op i ->
        if (i*2 < 3 || i*2 > 3) then
          case op of
            B ->
              i * 2 + 3
            C ->
              i * 2 + 4
         else
           Debug.crash "i*2 /= 3"
```

**Comment by jvoigtlaender** [comment]
Yes, sure, there are infinitely many syntactic special cases that would allow successful analysis. And the compiler could pick a larger syntactic class than it currently does. Trying to "look through" let-expressions that don't affect the scrutinee of the inner case-expression etc. The question/trade-off then becomes where to stop, given that the general class of all expressions is not reachable for analysis. As mentioned, I'm not aware of a compiler that goes significantly farther than the Elm compiler in this regard.

**Comment by evancz** [comment]
If we can find compilers that do analysis that is aware of control flow (as is needed in the example with `if`) we should link about how they do it.

Otherwise, it's like @jvoigtlaender said, I don't know of any compiler that does exhaustiveness checking across multiple `case` expressions, and I don't think we should track it as an error if we are not even sure this is a decidable problem.
