### ISSUE TITLE
Getting wrong version of elm compiler through npm (on Windows)

### ISSUE THREAD

**Issue by kuznero** [elm-lang/elm-compiler#1490]
Installing elm through `npm install -g elm` installs v 0.17.0 instead of v 0.17.1 as it claims to. Has to install through elm platform instead.

**Comment by jvoigtlaender** [comment]
What evidence do you have for `npm install -g elm` installing 0.17.0 instead of 0.17.1?

Here is some evidence to the contrary: https://travis-ci.org/jvoigtlaender/pumping-regular#L154-L170

**Comment by kuznero** [comment]
Sorry for not stating that in the first place. This problem occurs on Windows. What evidence do you need?

**Comment by jvoigtlaender** [comment]
First of all, it's not so much that *I* need evidence, since I am not going to be the one to fix the issue (if there indeed is an issue, which I am not convinced of).

Second, since this seems not to be resolved-and-immediately-closed now, this is the wrong place to have this conversation. You should close the issue and open a new one at https://github.com/elm-lang/elm-platform/issues, because that repository is dealing with the installers, including the `npm` one.

And about what additional information should be in the issue description: definitely something like the console log I pointed to (on Travis, and which clearly showed that in that case 0.17.1 was installed). Even on Windows, there will be some output of `npm install` that one can look at, no? To see what was actually going on.

Finally, since you said Windows, I wonder whether it all is just a PATH setting error. Maybe you had installed 0.17.0 previously (maybe with the Windows installer), now tried to `npm install` 0.17.1 and that indeed downloaded 0.17.1 but put it in a place that your PATH does not cover, so still the old 0.17.0 gets picked up when you call `elm`? So any information (console output of PATH etc.) you can provide that refutes this conjecture, would be relevant as well.

**Comment by kuznero** [comment]
Thanks for clarifications! I will re-open this incident with more details on elm-platform.

**Comment by kuznero** [comment]
Tried to reproduce this on a clean Windows 7 but failed. So, I must have messed something up when using my old Windows machine. False alarm.
