### ISSUE TITLE
Inline `cmp` where possible

### ISSUE THREAD

**Issue by Skinney** [elm-lang/elm-compiler#1528]
Currently everything in elm is compared using a `cmp` function, specified in `elm-lang/core`. It turns out that calling this function, instead of just comparing values directly, has negative performance implications. Below is some numbers from `Skinney/elm-array-exploration` in the `get` benchmark. Core is the default implementation, Hamt is the implementation in the mentioned repo. The benchmark tests retrieving a value from an array containing 10.000 elements. The `get` function performs bounds checking (2 comparisons). The Hamt implementation also checks if the given index is located in the tail (+1 comparison).

```
Core: 9,595,004 ops/sec
Hamt: 7,552,036 ops/sec
Core, inline cmp: 11,566,791 ops/sec
Hamt, inline cmp: 10,244,497 ops/sec
```

`cmp` was inlined by manually editing the `get` function, replacing the `cmp` function with the operator that made sense (`<`, `>`, `<=`, `>=`).

As comparison (and `===` for that matter) operators are well defined for primitive types in javascript, inlining them in cases where it makes sense (strings and numbers) could lead to a performance increase.

**Comment by evancz** [comment]
> It turns out that calling this function, instead of just comparing values directly, has negative performance implications.

I need you to be more specific. Do you mean that putting in `<` is faster?

If so, that is a fine idea, but it requires that types are tracked all the way through to the optimization phase because you cannot say `tuple1 < tuple2` in JS and get something reasonable. This type information is not available during code gen, and that would be a huge project.

When that *does* happen though, there are all sorts of optimizations we can make. Marking integers and floats with `4|0` and `+4` such that we get the special cased optimizations for asm.js for example. Point is, this would necessarily be part of a much larger project, and be an obvious thing to do in that setting. So if I have understood correctly, I think this should be closed because it doesn't achieve any goal to track it here.

**Comment by evancz** [comment]
Also, if you make the same change to the core implementation, does it also get faster?

**Comment by Skinney** [comment]
Yes, I meant replacing `cmp` with whatever operator makes sense `<`, `>`, `>=`, `<=`.

Can also confirm that this makes the core implementation faster, have updated the original entry.

**Comment by evancz** [comment]
Okay, this requires tons of infrastructure work that won't happen for a while.

When it does, this will be one of the first things we can do.

So I don't think it makes sense to keep tracking as a one-off issue.
