### ISSUE TITLE
[New Parser] reports error on `.` operator, even in valid use

### ISSUE THREAD

**Issue by Skinney** [elm-lang/elm-compiler#1532]
Got the following error message

```
-- PARSE ERROR -------------------------------------------------------- Main.elm

I was not expecting this dot.

12|         |> List.map (.category >> identity)
                         ^
Dots are for record access and decimal points, so they cannot float around on
their own. Maybe there is some extra whitespace?

Detected errors in 1 module.
```

For the following code:

```elm
module Main exposing (..)

import Html exposing (text)


main =
    text "Hello world!"


locations =
    [ { category = "Blah" } ]
        |> List.map (.category >> identity)
```

**Comment by evancz** [comment]
Thanks for the report @Skinney, should be fixed now!

@rtfeldman, a smaller SSCCE would be:

```elm
getName = (.name)
```

The problem was committing too aggressively to the `(+)` interpretation, so it saw `(.` and thought that dot is not a valid symbol. I have added this case to the compiler tests in the commit that fixes the parser.

**Comment by rtfeldman** [comment]
@evancz ah, nice!

This actually suggested a cool refactor to the arithmetic fuzz tests: https://github.com/elm-lang/core/pull/786/commits/c4b9fbf9c666e45ef4f0ce2d0e25a4b10ac115c7#diff-31c71c7f5985f526d8b80487f9ad3867
