### ISSUE TITLE
[New parser] Cannot pattern match on bools

### ISSUE THREAD

**Issue by mgold** [elm-lang/elm-compiler#1539]
SSCCE:
```elm
bool b =
    case b of
        True ->
            1

        False ->
            2
```

Error:
```
-- NAMING ERROR ----------------------------------------------- ./src/Shrink.elm

Cannot find pattern `True`

5|         True ->
           ^^^^
```

It's fair to say that this should be an `if` instead, but sometimes pattern matching on tuples of bools is useful.

**Comment by simonh1000** [comment]
+1

**Comment by evancz** [comment]
Thanks for the report @mgold, should be fixed by the latest commit.

Also, @simonh1000, please do not do +1 on issues. It clutters threads. You can do the inline ones if you really want, but issues are inherently not a voting system. The set of people who know about the Elm GitHub repos is a tiny subset of all Elm users, so it is a very warped view of what's going on.

**Comment by Birowsky** [comment]
@evancz could you provide a binary with this fix?
