### ISSUE TITLE
Type Inference Failure with Anonymous Functions

### ISSUE THREAD

**Issue by cscalfani** [elm-lang/elm-compiler#1590]
In the following code snippet, `compilerError` and `noCompileError` are semantically equivalent yet the type inference acts differently causing a compiler error.

```elm

concat : String -> something -> String
concat s1 something =
    s1 ++ (toString something)


compilerError : String
compilerError =
    concat "string"
        |> (\doIt -> (doIt "") ++ (doIt 1))


noCompilerError : String
noCompilerError =
    let
        doIt =
            concat "string"
    in
        (doIt "") ++ (doIt 1)
```

**Comment by JoeyEremondi** [comment]
Unfortunately, this is how Elm is supposed to behave, and I don't think there's a good way around this without requiring annotations in more cases.

Elm, Haskell, ML, and many other typed functional languages are based on Hindley-Milner inference. The "magic" that makes Hindley-Milner work without type annotations is something called Let-generalization. When a value is defined in a let-block, the typechecker *generalizes* over any free unification variables in it.

So in your first case, the compiler does the following:
* Sees the call to `concat : String -> something -> String`, and replace `something` with a new unification variable, say `A`
* Sees the call to `doIt ""` and generate the constraint `A === String`
* Sees the call to `doIt 1` and generate the constraint `A === Int`
* See that these constraints have no solution, and fail

However, in your second case, it does the following:
* Sees the call to `concat : String -> something -> String`, and replace `something` with a new unification variable, say `A`
* Reaches the `let` definition of `doIt`, see that `A` has no constraints on it, and give `doIt` the type `a -> String`.
* Sees the call to `doIt ""`, replace `a` with a new unification variable `B` and generate the constraint `B === String`
* Sees the call to `doIt 1`,  replace `a` with a new unification variable `C`, and generate the constraint `C === Int`

Basically, the `let` tells the compiler that this value can be considered polymorphic. Without it, it thinks there needs to be a *single* type for the argument to `doIt`.

There are [type systems that don't use let-generalization](http://www.cs.cmu.edu/~joshuad/papers/bidir/), but they don't have the property of "you can remove any annotations and everything will still typecheck." They rely on user-provided type signatures to determine what functions to consider polymorphic. The problem of deciding where to put the polymorphism is, I believe, undecidable in general. So we either need the programmer to tell us, or we pick a spot to always do it. Elm opts for the second.

Note that top-level values, like function definitions, are all implicitly in a let-block, which is why you can define top level polymorphic functions outside of a let.

**Comment by cscalfani** [comment]
Thanks for the detailed explanation.

What I don't understand is what would be the harm in treating anonymous functions polymorphically?

**Comment by JoeyEremondi** [comment]
So, that's a complicated question.

The first thing to realize is that `String -> something -> String` is actually `forall something . String -> something -> String` i.e. polymorphism is explicitly scoped, but "nested polymorphism" isn't allowed, because for nesting any more than 2 levels deep, inference becomes undecidable.

So then, the question is, what type would you infer for `foo x = (x, (\y -> (x,y))`? If you reached the end of the lambda and treated it as polymorphic, it would have type `forall a . (a -> (a, forall b. b -> (a,b))`. But now we've got nested polymorphism, which causes all sorts of problems.

We also have to consider the dual of this: when do we decide to instantiate a polymorphic function to its definite type?

* With Hinldey-Milner, it's easy. We always instantiate at the use of a variable, because the only things that are polymorphic are let-bound variables.
* With [System-F](https://en.wikipedia.org/wiki/System_F) (which allows for the nested polymorphism I talked about), you can instantiate anywhere, but you have to explicitly use "type application" i.e. tell the compiler *every time* you instantiate a polymorphic value, which makes the code really ugly.
* With a [bidirectional system](http://www.cs.cmu.edu/~joshuad/papers/bidir/), you can have nested polymorphism, and use subtyping to determine when to instantiate, but again, this requires that you have *some* annotations, and carries its own host of difficulties.

So for your example, it's too hard of a problem for the compiler to simultaneously figure out what the type of your anonymous function is, and figure out *for every single value* whether it needs to be instantiated to a different type, without some annotations from the developer.

**Comment by cscalfani** [comment]
Since Hindley-Milner only allows for polymorphic let-bound variables, why couldn't the compiler "rewrite" anonymous functions in terms of a `let`?

Imagine a preprocessor that would rewrite the `compilerError` function to the `noCompilerError` and then pass it to the Elm compiler. That certainly would work.

Except, my suggestion is to have the compiler do this internally. This could be done on an early pass.

**Comment by evancz** [comment]
Thanks for providing a great overview of why this happens @JoeyEremondi!
