### ISSUE TITLE
Include for non-module code management

### ISSUE THREAD

**Issue by welderone** [elm-lang/elm-compiler#1624]
Since inter Module communication is painful and not actually recommended, separating code into files that could be included uniquely would allow separating code into more maintainable named files.

**Comment by evancz** [comment]
I do not understand this suggestion. I can tell it is a feature request though, which we generally do not track in github issues though, so I will close.

If the idea is for files and modules to no longer have a one-to-one correspondence, I will not change that. It sounds like the root question here is about how to write large applications. You seem to want to want to have your code organized around "visual components" rather than data structures specific to your app. I think the folks on slack can help you get a better idea of how to structure this code.
