### ISSUE TITLE
Runtime Error: TypeError: fun is not a function

### ISSUE THREAD

**Issue by nukisman** [elm-lang/elm-compiler#1629]
Open the test app in [Ellie](https://ellie-app.com/3WKrBqygsrJa1/0) or reproduce in your local project.

It compiles but fail with runtime TypeError.

It uses package [jvoigtlaender/elm-memo](https://github.com/jvoigtlaender/elm-memo/tree/2.0.5) which is pure Elm, non JS

Chrome 60.0.3112.90
macOS Sierra 10.12.6

**Comment by nukisman** [comment]
It seems to be the problem in dependency of` jvoigtlaender/elm-memo` - `elm-lang/lazy` (it contains native JS)

**Comment by jvoigtlaender** [comment]
No, the dependency on native code is not the problem. The problem is that the current Elm compiler does not treat certain recursions correctly. It is fixed in the upcoming Elm 0.19 version according to what I have heard.

However, `jvoigtlaender/elm-memo` itself will not be available in Elm 0.19 anymore, due to the discontinuation of `elm-lang/lazy` (https://github.com/elm-lang/lazy/commit/c9c3f8525d22978cd7ee6e463ebf208f30fa1f91).

**Comment by jvoigtlaender** [comment]
To see that it is currently just a problem of the compiler's treatment of recursion, you can just switch around the definition order of `fib` and `mfib` in your Ellie app. Suddenly it will work.

**Comment by nukisman** [comment]
@jvoigtlaender Ok, so as it is fixed in 0.19 I close the issue.

**Comment by nukisman** [comment]
@jvoigtlaender 
Is this recursion treatment problem actual for pure code without native dependencies?

**Comment by jvoigtlaender** [comment]
Yes, it very much is. Many examples exist in issues in this repository and/or the elm-lang/core repository.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/elm-compiler/issues/1591
