### ISSUE TITLE
main cannot be of type a

### ISSUE THREAD

**Issue by rtavenner** [elm-lang/elm-compiler#1634]
When compiling this code:

    main = Debug.crash "Todo"

I get:

    Detected errors in 1 module. 
    ==================================== ERRORS ====================================
    
    
    -- BAD MAIN TYPE --------------------------------------------------------------- 
    
    The `main` value has an unsupported type. 
    
    2| main = Debug.crash "Todo"
    
    I need Html, Svg, or a Program so I have something to render on screen, but you gave me:
        a 

I think this should compile, because `Debug.crash "Todo"` has type `a`, which can be specialized to type `Html msg`.

**Comment by zwilias** [comment]
Like the error mentions, there are several valid types for `main`. While `a` can be specialized to all 3 of them, it can't know which one it should be, since Elm needs different logic for hooking up a virtual-dom node-as-main vs an html program vs a `Platform.Program`. 

There are two ways to handle this:
- arbitrarily picking one of those type to specialize to (would be a little weird)
- giving an error with the valid types. Arguable, that error could mention "you can add a type signature", but since you can't create a useful program with a crashing `main`, that would only ever be useful in this specific case, and be a possible source of confusion in every other case.

Note that adding a type signature for one of those types makes the error go away.

**Comment by rtavenner** [comment]
Note that in all 3 cases, the end result is the same: the program crashes as soon as it is opened. So arbitrarily picking one isn't that bad. 
On the other hand, if Elm ever gets typeclasses (I hope not, but that's another topic), it would break the assumption that any supertype of Html, Svg, and Program is guaranteed to crash.

At the time I came across this, I just wanted to make sure the rest of my code compiled before getting back to my main function, and figuring out what was going on here was a distraction.

This issue caused me some confusion, because I'm used to `Debug.crash "Todo"` being a valid placeholder anywhere in the program.

I don't know what the best solution is.

**Comment by evancz** [comment]
Here are some facts:

  - This must have been true for a couple years now, and this is the first time someone mentioned it.
  - It is not clear what would constitute "good behavior" in this case.
  - You can always say `text <| Debug.crash "TODO"` or `text "TODO"` and it will work.

So my plan is to leave it as is. If in discussions on slack or elsewhere, folks find a better trade-off, we should open a new issue outlining that alternative conclusion.
