### ISSUE TITLE
Inconsistency between polymorphic functions that are statically defined or passed as an argument

### ISSUE THREAD

**Issue by edkv** [elm-lang/elm-compiler#1658]
Suppose that we want to apply a polymorphic function to some values of different types. Here are two examples:
```elm
test1 : (a -> String) -> List String
test1 convert =
    [ convert 1
    , convert "Hello"
    ]
```
```elm
test2 : List String
test2 =
    let
        convert : a -> String
        convert _ =
            ""
    in
    [ convert 1
    , convert "Hello"
    ]
```
`test2` compiles just fine while `test1`  leads to:
```
The argument to function convert is causing a mismatch.

Function convert is expecting the argument to be:

a

But it is:

number

Hint: Your type annotation uses type variable a which means any type of value can flow
through. Your code is saying it CANNOT be anything though! Maybe change your type
annotation to be more specific? Maybe the code has a problem? More at:
https://github.com/elm-lang/elm-compiler/blob/0.18.0/hints/type-annotations.md
```
Both `convert` functions are defined as `a -> String` and the only difference is that in the first example that function is passed as an argument to another one. Should the compiler allow the first example as well? Or are there any reasons to not allow it that are not obvious here?

Elm version: 0.18.

**Comment by zwilias** [comment]
This is known as [let polymophism](https://genericlanguage.wordpress.com/2010/08/30/let%C2%A0polymorphism/). The primary reason for only allowing this for `let` bound variable is - if I'm not mistaken - because type inference for higher-rank polymorphism is undecidable.

If you're interested in the details:

To show _how_ this introduces higher-rank polymorphism, we can specify the scope of the polymorphic variable using `forall`. What you've written is essentially this:
```elm
test1 : forall a. (a -> String) -> List String
```
Which means "for all types `a`, given a function to go from `a` to `String`, `test1` returns a `List String`".
So, the `a` is _constant_ through that entire declaration: it can be bound only to a single type.

The way you're using it, however, is something like:
```elm
test1 : (forall a. a -> String) -> List String
```
Which means, roughly, "given a function that can go from any `a` to `String`, `test1` returns a `List String`"

This means Hindley Milner is not longer sufficient for type inference, but rather you need something like System F. Incomplete but decidable type inference implementation for this exist, but a more powerful type system usually brings more complexity with it, too.

Given the above type annotations, it may also be a little more clear why this _does_ work for a `let` bound variable: the `forall a.` there isn't talking about the entire `test2` function, but only the `convert` function.

**Comment by edkv** [comment]
@zwilias Thanks for the explanation. Closing this as it's a known behaviour and not a bug. I'll find another way to accomplish what I'm trying to do.
