### ISSUE TITLE
Anonymous functions that refer back to the variable they're being used to initialize leads to undefined value runtime errors

### ISSUE THREAD

**Issue by alex-tan** [elm-lang/elm-compiler#1688]
Example (see the assignment to `a` in the update function):

```elm
import Html exposing (beginnerProgram, div, button, text)
import Html.Events exposing (onClick)

main =
  beginnerProgram { model = { a = 1, b = 2 }, view = view, update = update }

view model =
  let
    { a, b } = model
  in
  div []
    [ div [] [ text (toString a) ]
    , button [ onClick Increment ] [ text "+" ]
    ]

type alias Model =
  { a : Int
  , b : Int
  }
type Msg = Increment

update msg model =
  case msg of
    Increment ->
      let
        a = model
        |> (\m -> a)
      in
      a
```

Took me a while to hunt this down. Would be nice to have a compiler error message for this.

Browser: Safari (11.0.3), OS X 10.13.3
Elm: 0.18

**Comment by zwilias** [comment]
Thanks for the report!

In 0.19, this particular example will refuse to compile with the familiar "cyclic value" error.

The general idea is that cyclic values will no longer be allowed, except if there is at least one function (rather than just lambda) involved in the cyclic chain. This should still allow expressing whatever you need when you do need cyclic stuff, but hopefully prevent a bunch of silly-yet-easy-to-make mistakes.

Hope this helps!
