### ISSUE TITLE
Can compile invalid Elm with self-reference in closure. Allows undefined value and can cause runtime error.

### ISSUE THREAD

**Issue by mcapodici** [elm-lang/elm-compiler#1689]
The following program defines badboy of type string, which uses itself in it's definition. I'm not sure if this should recurse (or not compile at all), but what happens is you see 'undefined' on the screen once compiled.

This allowed me to introduce a crash in another program where I was trying to access a property on a record set up a similar way to badboy below.

Windows 10 / Chrome / Elm 0.18.0

    module Main exposing (..)

    import Html

    main : Program Never () ()
    main =
        Html.program
            { init =
                ( ()
                , Cmd.none
                )
            , view =
                \_ ->
                    let
                        badboy =
                            Just "hello"
                                |> Maybe.map (\_ -> badboy)
                                |> Maybe.withDefault ""
                    in
                        Html.div [] [ Html.text badboy ]
            , update = \_ mdl -> ( mdl, Cmd.none )
            , subscriptions = \_ -> Sub.none
            }

**Comment by zwilias** [comment]
Thanks for the report!

In 0.19, this particular example will refuse to compile with the familiar "cyclic value" error. 

The general idea is that cyclic values will no longer be allowed, except if there is at least one _function_ (rather than just _lambda_) involved in the cyclic chain. This should still allow expressing whatever you need when you _do_ need cyclic stuff, but hopefully prevent a bunch of silly-yet-easy-to-make mistakes.

Hope this helps!
