### ISSUE TITLE
Unable to generalize a type variable - another example

### ISSUE THREAD

**Issue by mzero** [elm-lang/elm-compiler#1690]
As instructed by the compiler, I'm reporting this. I see that recently a bunch of these were aggregated and closed... but a quick inspection made me think my case might be different, so I'm reporting it:

Minimal case:
```elm
type M
  = M1 Int

desc1 : { project : Int -> String }
desc1 = { project = toString }

deconstruct : (d -> a -> String) -> M -> String
deconstruct f m = case m of
  M1 a -> f desc1 a
```
This results in:
> :: elm-make: It looks like something went wrong with the type inference algorithm.
> :: Unable to generalize a type variable. It is not unranked.
> :: Please create a minimal example that triggers this problem and report it 

A more fleshed out example that shows my motivation:
```elm
type M
  = M1 Int
  | M2 String

type alias Desc a =
  { print : a -> String
  , count : a -> Int
  }

descM1 : Desc Int
descM1 = Desc toString identity

descM2 : Desc String
descM2 = Desc identity String.length

deconstruct : (d -> a -> r) -> M -> r
deconstruct f m = case m of
  M1 a -> f descM1 a
  M2 a -> f descM2 a

printM : M -> String
printM = deconstruct .print

countM : M -> Int
countM = deconstruct .count
```

Elm 0.18, 'natch!

**Comment by zwilias** [comment]
In your minimal case, the type signature says "Give me a function with two type variables and a `String` result, an `M` and I'll give you a `String`". So judging by the type signatures alone, that means I can pass it `String.repeat`.

Clearly that doesn't make sense, but it points to the underlying issue - there _are_ in fact constraints on what `d` and `a` may be. In this case, those constraints can't meaningfully be expressed in Elm. (It's something like `Desc a -> a -> r` where the value of the type variable `a` depends on the value of `M`)

The error isn't very helpful, though it's better in 0.19:

![image](https://user-images.githubusercontent.com/1038427/37511607-c1ad5290-28ff-11e8-9ba1-27d5a279842c.png)

The error for the full example is similar.

---

Thanks for the report, though! Since this won't result in an `unable to generalize a type variable` error in 0.19, I'll close this for now. Always welcome on Slack to discuss what your options are 😃 

I think the closest you can reasonably get to this is to flip the way `Desc` works around from being polymorphic in the input and having different sets of operations for the different values of `M`, to being polymorphic in the output and each describing a single operation for all values of `M`: https://ellie-app.com/m82mcCJRza1/0
