### ISSUE TITLE
Pattern matching in let expressions not working

### ISSUE THREAD

**Issue by grzegorzbalcerek** [elm-lang/elm-compiler#360]
maybeShow1 (Just value) =
  asText value

--maybeShow2 justValue =
--  let Just value = justValue in asText value

maybeShow3 justValue =
  let (Just value) = justValue in asText value

maybeShow4 justValue =
  let value = maybe 0.0 id justValue in asText value

main = maybeShow3 <| readFloat ("123.10")

The maybeShow1 and maybeShow4 work fine.
However,
maybeShow2 does not compile.
maybeShow3 compiles but fails at runtime (at least on my Internet Explorer on Windows 8).

**Comment by evancz** [comment]
I'm not sure what needs to happen here, so I am going to close it and ask that if anything is unresolved we open new issues explaining exactly the problem.

I don't think we can support pattern matches on things like this:

```elm
let Just x = something
in
    ...
```

because that would imply that we could properly pattern match on

```elm
let f Just x = ...
in
    ...
```

If there is something going wrong with code gen in one of these cases, let's have an issue specifically for that.
