### ISSUE TITLE
Feature Request: Arbitrary (First-order) Datatypes in Ports

### ISSUE THREAD

**Issue by maxsnew** [elm-lang/elm-compiler#490]
This seems pretty simple to implement:
```haskell
data Foo a = Bar String
           | Baz (Foo a) Int
x = Bar "bleh"
y = Baz x 7
```
then `x` and `y` could be serialized to the following javascript (field names could easily be something else):
```javascript
var x = { _ctor: "Bar", _0: "bleh" }
var y = { _ctor: "Baz", _0: x, _1: 7 }
```
The only problem I see with this is that the serialization of `Maybe` would be inconsistent with this.

Right now it's actually impossible to serialize a Sum type. Even if we're unsure about doing this in general, we definitely need to at least support the `Either` type. Currently I'm doing the following to get around this limitation
```haskell
type Either' a b = (Maybe a, Maybe b)
```
where I ignore the 2nd value if the first one is non-null, but this is obviously suboptimal.

**Comment by thSoft** [comment]
As of now, a workaround is to pass Json.Values through ports and Json.Decode/Encode them.

**Comment by rtfeldman** [comment]
I'm a bit late to the party here, but has anyone considered exposing (and mandating the use of) explicit constructor functions? For example:

`Elm.Just(42)`
`Elm.Nothing()`

I see a few benefits to this:

1. The intermediate representation is no longer exposed, so it can change between versions without breaking existing code.
2. You can no longer accidentally use this API for dirty hacks; all the exposed constructors only permit doing things "the right way," so you'd have to deliberately avoid using them in order to do things the wrong way.
2. This looks more like the equivalent Elm code.

Thoughts?

**Comment by knuton** [comment]
I pitched an idea to Evan last week which boils down to registering destructors (in-port) and constructors (out-port) for arbitrary representations of variant types. We agreed that I'd write it up here to get some feedback.

The main motivation is to arrive at a unified approach that subsumes currently port-compatible ADTs while allowing arbitrary data representations outside of Elm. This picks up on [@rtfeldman's proposal](https://github.com/elm-lang/elm-compiler/issues/490#issuecomment-76348319).

I very much tried to think with my JS cap on: How might I want to deal with this data in a JS codebase? (Hence trying to avoid `if (foo[0] === 'Bar') return foo[1];`.)

Credo:

> Ports are about writing natural and colloquial code in both Elm and JS, not forcing an approach on JS people.

Benefits:

- No need to fight over representation: Outside representation can be "idiomatic" in various JS styles
- Conversion of e.g. `Maybe` fits into this approach naturally
- Be compatible with `Data.Aeson.TH` if you want
- The default behavior can be convenient and simple, e.g. *TaggedObject* going in and out
- Conversion and border policing collapse into one process, we incur low overhead

I'll reuse the example from above:

```elm
data Foo a = Bar a
           | Baz (Foo a) Int
```

Let's assume that in my JS I represent those as (assuming `Foo String`)

```js
{ kind: 'Bar', size: '40sqm' }
{ kind: 'Baz', bar: { ... }, rooms: 5 }
```

Other encodings abound, e.g. [OOP style](https://gist.github.com/knuton/50555114bb520a601347).

## Destructing Outside Representations (in-ports)

```elm
port : Signal (Foo String)
```

The basic idea for conversion at an in-port with type `T` is to register a function that knows how to transform an incoming value when given access to all of the constructors of `T`. The trick is to only accept conversion results when they are constructed with our constructors. This allows us to assure that ultimately incoming values are of the right form.

So in this case, for whatever outside representation `OuterFoo String` of `Foo String` we need a function

```elm
   OuterFoo String
-> (String -> Foo String) -- Bar
-> (Foo String -> Int -> Foo String) -- Baz
-> Foo String
```

for example suppose the following function is registered for `Foo`

```js
function fooIn(val, Bar, Baz) {
  switch (val.tag) {
    case 'Bar': return Bar(val.size);
    case 'Baz': return Baz(val.bar, val.rooms);
  }
}
```

`Bar` and `Baz` are not simple constructors, but are guarded -- this is the border policing:

What does `Bar` do?
- If `val.size` is a string, construct a `Foo String`
- Otherwise, throw

What does `Baz` do?
- Look up the converter for `Foo`, i.e. `fooIn`
- If `fooIn(val.bar)` returns and `val.rooms` is a number, construct a `Foo String`
- Otherwise, throw

What happens with the return value of `fooIn`?
- Check whether it was constructed with either `Bar` or `Baz`, throw if not

Note that this construction process is recursive, that is, nested ADTs can be sent through ports.

## Constructing Outside Representations (out-ports)

The idea is similar but now the converter is called with a tag (probably a string?) and the data, from which it constructs whichever representation desired.

## Converter Registration

A default converter (e.g. from and to *TaggedObject*) can be used when no converter is registered for a type. Converters can be registered globally for all types and/or per type.

Because ADTs may appear nested inside ADTs or records, we need to do one of two things:
- Fall back to a default if we don't have a converter for a type
- Throw if we don't have a converter for a type (this is basically [what happens now at compile time](https://github.com/johnpmayer/Elm/blob/master/compiler/Generate/JavaScript/Ports.hs#L125))
  - Either when initializing the Elm app (requires type traversal on defined ports)
  - Or on processing incoming/outgoing values
  
## Builtins

The Elm runtime could make use of this approach to register a *TaggedObject* converter as default, while pre-registering special converters for builtin types such as `Maybe`, `List`, etc.

---

I have more details, but this is too long alreay. (Sorry!) What do you think?

**Comment by evancz** [comment]
I am trying to clean up the issues on these repos. My goal is for issues on repos like `elm-compiler` and `elm-repl` are about specific bugs. It is not working to manage proposals and stuff that requires changes to the language here, so I am devising a way of keeping track of all this stuff in a transparent way.

The idea is that it doesn't super matter where the proposal is opened, but we should collect related ideas in certain places so we can look at them as a collection of issues and find a coherent solution that addresses them all as much as possible. So I'm gonna close this and reference https://github.com/elm-lang/elm-plans/issues/17 which is collecting a bunch of port problems.

If there is more to say about this idea, we should continue on this thread. The fact that is closed is more about decluttering stuff!

**Comment by thewoolleyman** [comment]
Hello,

What is the status of this?  https://github.com/elm-lang/elm-plans/issues/17 is still open with no status, but the repo is "deprecated"...

Thanks,
-- Chad

**Comment by dullbananas** [comment]
@evancz what is the progress on this
