### ISSUE TITLE
Collage extension to use quadraticCurveTo()

### ISSUE THREAD

**Issue by andreywix** [elm-lang/elm-compiler#683]
I'd like to have this functionality but it seems that it's too small of a thing to write a library for, so I was wondering how could I contribute to the core?

I believe that all that is needed to be done is add a function traceQuadratic to this file (https://github.com/elm-lang/Elm/blob/a38e0c15ac0ba3683f548606781d029706fcb6b6/runtime/Render/Collage.js) and reuse trace() with lineTo() switched to quadraticCurveTo().

Thank you!

**Comment by evancz** [comment]
Sorry for the no-response here, I am slowly learning how to handle issues where I don't actually know the answer but think it's a good idea.

I am going to reference https://github.com/elm-lang/core/issues/332 so we can find this idea there. It requires some API redesign to make it work out right and I'm not sure how that should look exactly right now. The new theory is that you should err on the side of closing issues because they will come up again no matter what, and hopefully at that time, it'll be clearer how to address them :)
