### ISSUE TITLE
Fixity declaration on shadowed operator causes parsing error

### ISSUE THREAD

**Issue by pseudonom** [elm-lang/elm-compiler#843]
As far as I understand it, Elm allows you to shadow imported functions with locally defined ones. However, adding a fixity declaration to a shadowed operator causes a parse error. For example,
http://share-elm.com/sprout/5483dcb1e4b00800031ffe99. This seems inconsistent.

**Comment by evancz** [comment]
The error now looks like this:

```
-- SYNTAX ERROR ------------------------------------------------------- hats.elm

The infix declarations for (~) must be removed.

0| 
1| infixl 4 ~
2| ^^^^^^^^^^

The precedence and associativity can only be set in one place, and
this information has already been set somewhere else.

```

It may make sense to make this more flexible, but we should talk about it in the context of adding a new feature instead of a weird parse error. My inclination is to only allow these declarations in the files where the operator is defined as a top level thing, and then attach the fixity info to particular variables. This is a decent sized change to the parser / AST, but that might be the way to go eventually.
