### ISSUE TITLE
Multiple imports are not additive

### ISSUE THREAD

**Issue by seancorfield** [elm-lang/elm-compiler#874]
See this thread with code examples: https://groups.google.com/forum/#!msg/elm-discuss/w3VCAIHCBLk/403YO_cXVskJ

It seems that the first explicit import overrides the default import, e.g., `import Signal (map, foldp)` hides the `Signal` type constructor.

It seems that subsequent explicit imports are ignored, e.g., after `import Signal (Signal)` if you do `import Signal (map, foldp)` then `map` and `foldp` are still "not found".

In addition, if you do `import List (map)`, the `List` type constructor still works which suggests that it doesn't follow the same rules somehow.

**Comment by evancz** [comment]
Should they be?

`List` is a special type because it is tied to syntax. Writing `[1,2,3]` requires that the `List` type is available, so the compiler actually knows about that type. I'm not sure how to fix that or if it is definitely broken. I'd be curious how Haskell or OCaml handle this.

As for additive or not, I had not thought about people adding many different lines. The design right now is, I want people to be able to override the default imports. If they do not want `Maybe(..)` in scope, they should be able to do `import Maybe ()` and get rid of it.

This decision was made when the set of default imports was much more extensive though, so it may not make sense anymore. When `List` is default importing `map`, `foldl`, `filter`, etc. making things additive seems limiting.

Why do you think it's good to write many imports? Or is this mainly about the interaction with default imports?

**Comment by seancorfield** [comment]
I think the most pertinent argument is what would most people expect the following to do:

    import Signal (map)
    import Signal (foldp)

I think most people would expect that to import both `Signal.map` and `Signal.foldp` -- which is not what happens.

I also think that having `List` be "magic" is a bad idea: either you need to import type constructors or you don't -- the compiler knows that `main` has to have type `Element` or `Signal Element` but you can't declare either of those without adding explicit `import`s, yet you appear to be able to declare `List` types without an import. That isn't consistent.

**Comment by evancz** [comment]
I agree with this reasoning :) I'm not sure when I could get to this, but this seems like a great issue for someone looking to work on the compiler!

**Comment by hoosierEE** [comment]
`import Foo()` should NOT translate to `import none of Foo` :fire: My goodness.  Think of people coming from other languages, where it would be extremely surprising for something that looks like a function call (word followed by empty parens) to in fact mean (word unioned with the empty set).

Some alternatives:

* `deport Foo`
* `import -Foo`
* (personal preference) just don't import anything by default. A little more boilerplate in your main file won't kill language adoption (see also Java, C++, etc).

**Comment by evancz** [comment]
This should be much nicer in 0.15. Let's open a new issue if there are still problems in the latest release!

**Comment by hoosierEE** [comment]
Indeed imports are much nicer in 0.15, nice work!
