### ISSUE TITLE
Unifying comparable and appendable fails

### ISSUE THREAD

**Issue by drenninghoff** [elm-lang/elm-compiler#880]
The following code doesn't compile, even though it seems to be correct. There has to be some kind if issue when dealing with types that need to be appendable aswell as comparable.

```
renameVar : String -> Set String -> String
renameVar s l = if Set.member s l then renameVar (s ++ "'") l else s
```

it throws the error

```
Type mismatch between the following types on line 2, column 51 to 59:

       appendable

       comparable
```

**Comment by drenninghoff** [comment]
Another example: http://share-elm.com/sprout/54b2f16be4b05f9c59b24fe3

**Comment by jvoigtlaender** [comment]
Note also that the compile errors goes away if one floats the first argument of the recursive call outside with a `let`. So, in the first example, by replacing the right-hand side with `let t = s ++ "'" in if Set.member s l then renameVar t l else s`. That such a simple refactoring turns the error on/off itself seems suspicious.

**Comment by mgold** [comment]
Strings and Lists are both comparable and appendable, and Arrays may be both at some point in the future. So the compiler needs to solve the problem of overlapping constraints. The Haskell-inspired version is `thing : (comparable a, appendable a) => a` but I think we can do better than that.

**Comment by jvoigtlaender** [comment]
Does the compiler really have to "solve" for anything here? Note the type annotation on the function. So the compiler should not need to formulate/answer a question like "What `a` is both `comparable` and `appendable`?" (which would have the ambiguity/expressibility issues you mention). Instead, it only needs to ask "Is `String` a `comparable`? Is it also `appendable`?". These are easier questions that can be answered on the spot, not requiring a generalization like the collection of constraints you indicate in your Haskell type. Of course, whether it's at easy to do it just like that "on the spot" in the current structure of Elm's type-checker is another matter (and I have no idea, since I didn't take a look).

In other words, it is clear that there is not even hope for Elm to infer a type for this function:
```elm
f s = if Set.member s Set.empty then f (s++s) else s
```
currently (because its most general type isn't even expressible in Elm's type language). But in this function:
```elm
f s = if Set.member s Set.empty then f (s++"") else s
```
one might expect the `""` to provide enough information for the compiler to figure out that the type in question must be `String`, from which everything else falls into place. At least there is no argument here that Elm has no chance to find the type because it cannot express "overlapping constraints". And certainly that is even more so the case if the programmer even provides the type explicitly:
```elm
f : String -> String
f s = if Set.member s Set.empty then f (s++"") else s
```
No guessing on the compiler's part at all is really required here, right? (Of course, everything modulo "But the type-checker follows some specific strategy, and maybe that simply doesn't let him see the obvious thing here right away.")

**Comment by mgold** [comment]
I think your last modulo is spot-on -- the compiler (as I understand it) looks only at appendable and comparable, and then expects to unify that with string later. Hence my suggestion for an intermediate representation (`comparableAppendable` or what have you, which would also allow the first function to be typechecked).

**Comment by jvoigtlaender** [comment]
It would be good if it were possible to express in what situations this issue exists and when not, and how the programmer might help the compiler. To the unsuspecting Elm user, it is completely obscure why
```elm
f : String -> String
f s = if Set.member s Set.empty then f (s++"") else s
```
suffers from this problem but
```elm
f : String -> String
f s = let t = s++"" in if Set.member s Set.empty then f t else s
```
does not. Is there some advice like "It is a good idea to float expressions outwards because ..."? What is the reason why your hypothesis "the compiler looks only at appendable and comparable, and then expects to unify that with string later" does not hit here?

**Comment by jvoigtlaender** [comment]
In fact, this works:
```elm
f : String -> String
f s = let artificial : String
          artificial = s
      in if Set.member s Set.empty then f (s++"") else s
```
Since the `artificial` binding does not do anything except for expressing that `s` is a string, and since that information is something the compiler already *has* at that point, I do not agree that this is something that "just is like so".

No, the compiler could even (conceptually, at least) add that `let artificial : String; artificial = s` stuff. Since that makes the example work, I don't think it is right to say the compiler simply cannot handle these cases because it does not know how to deal with `appendable` and `comparable` at once. Maybe instead it is really just a bug in the compiler which does not appropriately propagate some information it already has?

**Comment by jvoigtlaender** [comment]
I guess, it still comes down to "what are the rules for when the compiler propagates known type information". It does from a let binding into the body term, but not from a lambda binding (with known input type) into the body term?

**Comment by gsingh93** [comment]
I think I'm running into the same issue:
```
genPermalink : State -> String
genPermalink state = Dict.foldl (\k (_, b) acc -> if b then acc ++ k else acc) "" state.courseInfo
```
Using a let binding in the lambda and specifying the type of `k` fixes the issue.

**Comment by evancz** [comment]
Working from the `type-fixes` branch, this also is fine now. The following code goes through no problem:

```elm
import Set

renameVar : String -> Set.Set String -> String
renameVar s l =
  if Set.member s l then renameVar (s ++ "'") l else s
```
