### ISSUE TITLE
Abstract types omitted from elm-doc output

### ISSUE THREAD

**Issue by imeckler** [elm-lang/elm-compiler#881]
It appears that elm-doc fails to output the documentation for abstract types which are exported. A minimal example:
```elm
module DocTest (T) where
{-| A nice type.

# Types
@docs T

-}

{-| T is T -}
type T = T
```
`elm-doc DocTest.elm` outputs
```json
{
  "name": "DocTest",
  "comment": "A nice type.\n\n# Types\n@docs T",
  "aliases": [],
  "types": [],
  "values": []
}
```

**Comment by evancz** [comment]
When you say "for abstract types which are exported" are you implying that it works when they are not exported?

I suspect there's something going on because you are exporting the type but not any of the constructors. I think the right behavior would be to filter the constructors rather than the whole thing, which is what seems to be happening.

I think it won't be too crazy to fix if you want to take a look at [the elm-doc implementation](https://github.com/elm-lang/elm-compiler/blob/master/src/Docs.hs).

**Comment by imeckler** [comment]
No, I'm just saying that's is the reason it's a bug (that is, it wouldn't be a bug if the types weren't exported). I'll take a look at the implementation.

**Comment by imeckler** [comment]
Ok, I found the problem, but it's not exactly an easy fix to do it right.
```haskell
Parse.iParse Parse.header <$> readFile "DocTest.elm" 
```
gives
```haskell
Right (["DocTest"],Listing {_explicits = [Alias "T"], _open = False})
```
so `T` is being parsed as an alias in the export list (although is in the `unions` list returned by `categorizeDeclarations`) and so in the lookup on line 250, the name `T` is not present in the list of unions, and it's filtered out.

**Comment by evancz** [comment]
Made an issue to track all elm-doc bugs like this
