### ISSUE TITLE
Setting field causes compiler stackoverflow

### ISSUE THREAD

**Issue by jastice** [elm-lang/elm-compiler#885]
I can't even explain this error. Below is the minimal code I can reproduce a stackoverflow in the compiler with. It will only happen if the code is in the `case` and the `if`, and when setting a field of the `state` record based on an existing field in the record. Other constellations will cause a type error ("Infinite types are not allowed"). I am just really confused right now.

```elm
type alias State = { x: Float }
type Action = Key Int | Whatever

updateState: Action -> State -> State
updateState action state = 
  case action of
    Key key -> 
      if | key == 0 -> { state | z = state.x }
         | otherwise -> state
    _ -> state
```

**Comment by TheSeamau5** [comment]
hmm...  it's weird that the code even type checks. I'm guessing that this is a bug with the type checker

**Comment by jastice** [comment]
Probably related to #832, but I don't understand why the type would be infinite.

**Comment by mgold** [comment]
Since the `State` record is not extensible, trying to assign a `z` field not in the type definition should be a type error.

**Comment by awpr** [comment]
Here's a more-minimal repro:

updateState : {x:Float} -> {x:Float}
updateState state =
  if | False -> { state | z = state.x }
     | False -> state
     | False -> state

It only seems to happen when a branch with type { {x:Float} | z: ({x:Float}.x) } is unified with _two_ branches of type {x:Float}.  It doesn't seem to be related to unifying the {x:Float} in the type signature with  the if statement, because the following also triggers it:

updateState : {x:Float} -> ()
updateState state =
  let state' =
    if | False -> { state | z = state.x }
       | False -> state
       | False -> state
  in ()

I suspect it might be infinite recursion in Unify.gatherFields.

**Comment by evancz** [comment]
Record extension no longer exists, so this code cannot be written anymore.

That said, it is a "infinite type" thing. It is true that the annotation does not match the type of whatever the body is, but type inference actually infers the whole body before trying to match things up. This means we are getting the infinite type problem before we can say that the annotation does not match.
