### ISSUE TITLE
Constant is not sent to JS through port

### ISSUE THREAD

**Issue by lowdesertpunk** [elm-lang/elm-compiler#903]
Subscription to a port defined by a constant `Signal` is never called.

```elm
port setFoo : Signal Float
port setFoo = Signal.constant 1.0
```

**Comment by evancz** [comment]
This is expected behavior at the moment. It's kind of weird, but it also seems wrong to trigger an event on initialization knowing that no one will have added their `subscribe` to the port when things are actually getting initialized. Triggering an event on every `subscribe` also seems really weird. So it's really not clear what the right thing to do here, but we have thought about it a decent amount!

I'm going to close this because it is unclear how to resolve this for now.

If you have a specific usage scenario in mind, would you mind opening a new issue describing that? We can potentially add it to a meta issue about how ports currently work.
