### ISSUE TITLE
Parser confusion when using tabulation

### ISSUE THREAD

**Issue by MangelMaxime** [elm-lang/elm-compiler#928]
I have the following code :

```elm
route : Route (String -> Html)
route = match
    [
    	"/"                 :-> Home.display
    ,   "/src/Main.elm"   	:-> Home.display
    ,   "/CV.elm"         	:-> CV.display
    ] 	display404
```
When I execute my code I have this error :

```
Error in ./src/Routing.elm:

Parse error at (line 15, column 5):
unexpected "\t"
expecting whitespace, a newline, an expression or closing brace ']'
```

The line 15 is :
```elm
    "/"                 :-> Home.display
```

If I use spaces to indent and not tabulation, I don't have any problem. I think, this would be great to use allow space and tabulation as te tabulation as easier to play with in editor.

**Comment by evancz** [comment]
Tabs are not permitted in Elm source code for now because things are indentation sensitive. Depending on your editor settings, something might *look* aligned but not actually be.

I can imagine being stricter about formatting such that it becomes possible to use tabs, but that would need a much more formal proposal. I am going to close this for now, but as we make progress on projects like [elm-format](https://github.com/elm-lang/projects#elm-format) we can revisit this.
