### ISSUE TITLE
WIP: pattern match warnings

### ISSUE THREAD

**Issue by evancz** [elm-lang/elm-compiler#930]
This issue tracks work on pattern matching warnings (missing patterns, redundant patterns, etc.)

This work is happening on the [pattern-match-warnings](https://github.com/elm-lang/elm-compiler/blob/pattern-match-warnings/) branch, primarily in `src/Nitpick/`. These checks all need to happen after type inference. There are some other checks in this category (e.g. suggesting type annotations for top-level decls) so I have carved out a compiler phase called `Nitpick` for all of these things.

This branch should only be adding new files for now, I don't want to get bogged down in how exactly it gets integrated with everything else yet. We need to make sure the actual algorithm works and does not have insane performance characteristics.

Remaining tasks include:

- [x] Correct lookup of ADT tags in [`Nitpick.PatternMatches.lookupOtherCtors`](https://github.com/elm-lang/elm-compiler/blob/pattern-match-warnings/src/Nitpick/PatternMatches.hs), which currently should never trigger because the *type name* will not reliably match the *constructor names*.

- [x] Fill in `builtinDict`, I think this just needs to cover lists.

- [x] Address the question about intersecting record fields. What is the right thing here?

- [ ] Show some concrete cases that triggers this stuff along with the resulting warning.

- [x] Figure out the big-O of this thing. How does it relate to the number of patterns and the number of possible tags? (edit: general feeling that it is NP-hard)

- [ ] Find some cases that blow up, figure out how to bail when this happens.

A final thing to keep in mind is that we should start out with all of this stuff as warnings so that it can be in a patch release. Making certain things errors is a breaking change, and I'd like to ease people into this. Introduce warnings => turn on warnings by default => make some warnings errors.

cc @imeckler

**Comment by imeckler** [comment]
>  Address the question about intersecting record fields. What is the right thing here?
What is there currently is correct in the sense that a record match is irrefutable and covers everything (like a variable match) and the important thing about the value returned is that it has empty complement.

>  Figure out the big-O of this thing. How does it relate to the number of patterns and the number of possible tags?
According to [Lennart Augustsson](http://www.reddit.com/r/haskell/comments/34wa8y/exhaustiveness_checking_in_n_2_easy_steps/cqyxyw4), this problem is NP hard. The algorithm I use is essentially the same as the one described in [this paper](http://research.microsoft.com/en-us/um/people/simonpj/papers/pattern-matching/gadtpm.pdf) and is also the one that [Lennart uses](http://www.reddit.com/r/haskell/comments/2xp8ls/pdf_gadts_meet_their_match_patternmatching/cp24rzg) in his Haskell compilers, so I would assume it's pretty good.

**Comment by imeckler** [comment]
> Correct lookup of ADT tags in Nitpick.PatternMatches.lookupOtherCtors, which currently should never trigger because the ADT name will not reliably match the ADT tags.

Can you advise on this?

**Comment by imeckler** [comment]
Can you also advise on how to build/test properly? Currently `cabal build` fails on elm-doc code.

**Comment by evancz** [comment]
To build, I am just commenting out the whole elm-doc section of elm-compiler.cabal for now. Doesn't make sense to block on that.

On big-O, I understand this as "this *can* blow up, but it probably will not." Is there some way we can be more concrete about that? What characterizes problematic cases?

As an aside, is it really NP-hard within a single case-expression? The general problem of "will this code handle all errors?" seems to be because you could handle half of the patterns in one place and half in another, and now you are doing some control flow stuff, but I'm not interested in being that fancy.

As for the `lookupOtherCtors`, let's say I define a type like this:

```elm
type Maybe a = Nothing | Just a
```

The outer dictionary will have keys as module names and values as dicts of ADT info. We'll look up the `Maybe` library. Now we are looking at a dict of ADTs. The keys are the *type name* and the values hold al the tags. If we are looking up tag names, they will not be found. The *type name* never shows up in these dictionaries. Does that make sense?

**Comment by evancz** [comment]
Also, just saw the blog post, very cool!

It may make sense to talk about this real quick on video or something, but can you tell me what is wrong with the following process:

```
detectMissingPattern(casePatterns):
    for pattern in casePatterns:
        if pattern is  `_` or `x` or `{...}`:
           success

    // at this point, we know everything is an ADT constructor
    officialAdt = find one of the constructors in iAdts

    // we need to make sure the arguments to each constructor are complete
    // so we group all these args together
    ctorDict = group patterns by constructor

   check that officialAdt ctors and ctorDict keys overlap entirely

    for (ctor, argLists) in ctorDict:
        for i in [0..ctor.numArgs]:
            detectMissingPattern(argList[i])
```

It seems like this only needs to blow up if you want to do fancier stuff with guarded patterns?

**Comment by imeckler** [comment]
> Is there some way we can be more concrete about that? What characterizes problematic cases?

There are a few things in your pseudocode that I don't understand, but I can think of an easy bad case that might convince you that exhaustiveness checking seems to involve some kind of exponential blowup:
```haskell
type Three = A | B | C
f t = case t of
  (A, x2, x3, x4, ...) -> ...
  (x1, A, x3, x4, ...) -> ...
  (A, x2, A, x4, ...) -> ...
...
```
It causes the working set of uncovered patterns to double on every pattern:
```
[_] -- initially everything is uncovered
[(B,_,...), (C,_,...)] -- after reading the first match, everything without A in the first spot is uncovered.
[(B,B,...), (B,C,...), (C,B,...), (C,C,...)]
```
and so on.

If we could come up with a characterization of problematic cases, we might be able to win $1,000,000 :).
> As an aside, is it really NP-hard within a single case-expression?

This is my understanding. I tried to find a proof but couldn't find one.

**Comment by evancz** [comment]
Okay, great example, totally crushed the pseudocode :) I'll mark that bullet as resolved and add one about figuring out how/when to bail out of this.

**Comment by Apanatshka** [comment]
This sounds related to how type inference can explode in usual cases. But I guess the pattern matching case is more likely to show up in real code, therefore more important to have an automatic bail-out trigger for.

**Comment by karldray** [comment]
Maybe irrelevant now, but I saw this earlier and just got around to thinking about it. Exhaustiveness checking is NP-hard because [3-SAT](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem#3-satisfiability) can be reduced to it like this:

    (x1 or x2 or x3) and (x2 or x3 or not x4)

becomes

    case vars of
        (False, False, False, x4  ) -> ...
        (x1,    False, False, True) -> ...

The case expression matches exactly the variable assignments that fail to satisfy the given formula, so the formula is satisfiable iff the case expression is not exhausive.

**Comment by Apanatshka** [comment]
That's an elegant reduction :+1: I guess we can be sure now that exhaustiveness checking is NP-complete.

**Comment by evancz** [comment]
I don't totally follow the mapping, but that does not matter. @karldray, can you show a realistic pattern that has bad behavior and then say exactly what the big-O would be for that case? If we can figure out how typical it is and how bad it is, it'll be much easier to guard against.

**Comment by karldray** [comment]
Yeah, I think all realistic cases are ones we can check quickly, so the bailout logic would only be guarding against unusual stuff like generating Elm code to solve instances of k-SAT in the compiler.

The algorithm I had in mind is like the one @imeckler alluded to, but maintaining a factored representation of the not-yet-covered set of tuples of ADT constructors:

    initially:
        uncovered = {A,B,C} * {A,B,C} * {A,B,C} * ...
    after seeing (A, x2, x3, x4, ...):
        uncovered = {B,C} * {A,B,C} * {A,B,C} * ...
    after seeing (x1, A, x3, x4, ...):
        uncovered = {B,C} * {B,C} * {A,B,C} * ...

So there's no exponential blowup on his example.

When a pattern has non-wildcards in multiple positions, you combine the corresponding factors into their Cartesian product (and then remove the tuple represented by the pattern):

    after seeing (x1, B, B, x4, ...):
        uncovered = {B, C} * {BA, BC, CA, CB, CC} * ...

At each step:
- If any factor in `uncovered` is empty, then the patterns are exhaustive.
- If the cardinality of the uncovered set is larger than the sum of the cardinalities of the sets covered by the remaining patterns (all of which you can compute by multiplication), then the patterns are not exhaustive, because there's no way they could cover enough.
- Before incorporating the next pattern, if the size of the resulting `uncovered` data structure (which you can compute by multiplication) would be larger than some fixed limit, you give up on the check. This ensures linear runtime.

It would also be helpful to:
- skip patterns that are already completely covered (to avoid unnecessary product expansions)
- process the patterns in an order that delays large product expansions as much as possible (maybe just go in decreasing order of number of tuples covered by the pattern)

I'm pretty sure this (with a limit of ~1000 total elements in the `uncovered` data structure) would handle practically all legitimate cases.

**Comment by imeckler** [comment]
> I'm pretty sure this (with a limit of ~1000 total elements in the uncovered data structure) would handle practically all legitimate cases.

@karldray Do you think the simple algorithm I mentioned is sufficient for practically all legitimate cases and  "maintaining the factored representation" you mention is more trouble than it's worth in code complexity? This is what I expect.

**Comment by karldray** [comment]
Heh yeah, such a complex algorithm does feel like overkill here given that big case expressions are rare and should probably be refactored into small ones for clarity anyway. As an alternative to all this, it'd be nice if the language was more restrictive and required case expressions to be "obviously" exhaustive, for some simple definition of "obvious" that admits a simple fast checking algorithm, but I couldn't think of a way to do this without precluding any reasonable use cases.

It looks like your algorithm maintains a factored representation (i.e. the `_` in your example is my `{A,B,C}`), but you do the Cartesian products of all the "reduced" factors as soon as they become reduced instead of waiting until the positions actually appear together in a pattern. That seems fine to me.

I think the more important things are:
- visit the patterns roughly in order from "general" to "specific"
- do the cardinality-based shortcut for detecting non-exhaustiveness.

That way the user can have really specific patterns without necessarily causing a combinatorial explosion in the check. For example, these should be doable even if the tuples are length 10 and we have `Ten` instead of `Three`:

```elm
type Three = A | B | C

-- the (A, A, A, ...) would blow this up
-- but the less-specific patterns already guarantee exhaustiveness
exhaustive = case t of
    (A, A, A, A, A, ...) -> ...
    (A, x1, x2, x3, x4, ...) -> ...
    (B, x1, x2, x3, x4, ...) -> ...
    (C, x1, x2, x3, x4, ...) -> ...

-- the cardinality check would catch this before processing (A, A, A, ...)
not_exhaustive = case t of
    (A, A, A, A, A, ...) -> ...
    (B, x1, x2, x3, x4, ...) -> ...
```

**Comment by evancz** [comment]
Possibly relevant [paper](http://www.math.nagoya-u.ac.jp/~garrigue/papers/gadtspm.pdf)

**Comment by evancz** [comment]
@imeckler, I have merged this into the pattern-warnings branch along with TCE and some other optimizations.

I realized though that I'm not sure how to provide high quality error messages. It looks like right now we can find when something is incomplete, but without any context at all. So the report will say "What about pattern `Blah`?" even if that only shows up in a tuple in a list in a maybe. I am unsure how to provide that context right now. Do you have any thoughts on the proper presentation of these errors?

**Comment by evancz** [comment]
Alright, I made the error reporting pretty nice. I'm gonna close this since it is pretty much all set in the `next` branch.

Thanks for your hard work @imeckler!
