### ISSUE TITLE
compiler cannot unify the same type depending on import method

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/elm-compiler#959]
The Elm compiler throws a very strange error. If I import implicitly with `exposing (..)` in a different file, Main throws this error:

```elm
Error in src/Main.elm:

Type mismatch between the following types between lines 31 and 35:

        Model.BabyName.BabyName

        Model.BabyName.BabyName

    It is related to the following expression:

        ((\s pl ls -> (div [id "wrapper"])
                        <| [headerPane,leftPane s pl,mainPane s ls])
           <~ ((\_ -> _.signal) selected))
          ~ pickList
```

---

It seems this can be reproduced if you have multiple files depending on a single type definition, but importing it in different ways. For example:

```elm
module Types where
type Foo = Foo
```

```elm
module Bar where
import Types exposing (..) -- if this changes to (Foo) the error goes away

-- stuff
```

```elm
module Baz where 
import Types exposing (Foo) -- if this changes to (..) the error goes away

-- stuff
```

```elm
module Main where
import Baz exposing (..) -- implicit vs explicit here does not seem to matter
import Bar exposing (..) -- implicit vs explicit here does not seem to matter

-- stuff using Foo here should throw the odd in ablity to unify error
```

**Comment by SimSaladin** [comment]
Just to comment, I had similarly weird error message (Type mismatch between A and A) when importing the offending module always with 'exposing (..)'.

After clearing the elm make cache I got helpful messages about missing record fields I had just renamed in the type's definition but not in all its usages.

**Comment by rtfeldman** [comment]
We just ran into something similar (error message where it said a type mismatch between two identical types).

What was weirder was that the compiler ignored the error on subsequent builds of the same files; to reproduce the error, we had to touch a source file and *then* rebuild. If we didn't touch the file, the second build (and subsequent builds) would succeed even though the first one failed and we hadn't changed anything in between.

We ended up narrowing down the problem by inlining some type aliases; we had a type alias that was `type alias Foo = (Bar, Baz)` with `type alias Foo = String` and `type alias Baz = Int`, and we just replaced all of those with just `(String, Int`) - which got us a more normal error message.

(Turned out we were missing an argument to a function, so it was partially applied, leading to the error.)

Not sure if that helps, but there it is!

**Comment by evancz** [comment]
I cannot reproduce this with 0.15.1 or with master branch, so I'm going to close. Thanks for the report!

**Comment by evancz** [comment]
Oh, wait, is the example you provided incomplete?

Should there be code in each of the 4 modules? If so, please provide an example that definitely will trigger the bad behavior without modification and reopen this or open a new issue!

**Comment by Fresheyeball** [comment]
I will double check! Thanks for stay ontop of these!
