### ISSUE TITLE
Proposal : Union types get imported the same way as type aliases

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#968]
In Vector.elm, suppose you change 

```elm
type alias Vector = { x : Float , y : Float }
```

to

```elm
type Vector = Vector Float Float
```

then, in some other file using Vector.elm, for example, Matrix.elm, you'll need to change

```elm
import Vector exposing (Vector)
```

to 

```elm
import Vector exposing (Vector (..))
```

My proposal: both cases should look like this

```elm
import Vector exposing (Vector)
```

This is a small nitpick and can lead to confusion. This has already happened to me but with much larger record types where I had to turn them into union types because the type suddenly became recursive. 

I think that this is one of those things from Haskell that make no sense. If you want to use the Union Type unqualified, just expose it. If you don't want to use the Union Type unqualified, don't expose it. Why have these mutliple levels of exposure? (Not exposed, fully exposed, only the type annotation is exposed but not the constructor). Sure, there may be some syntactic convenience, but I find it unnecessary and needlessly confusing.

**Comment by mgold** [comment]
Being able to expose a union type but not its tags is how you create an opaque type. It's used all the time: the red-black tree behind the Dict library. My Socket.io library exposes the type but not the constructor of `type Socket = Socket` because underneath it's actually the native JS object. In a DSL, you can expose the type but hide the tags to be able to add new tags without a major release. And so on...

**Comment by jvoigtlaender** [comment]
Max, what you are talking about is hiding stuff on *export*. Hassan is talking about *import*s. For example, the `Dict` type is only opaque since the library does not export the constructors. If the library *did* export the constructors, trying to "hide" them on import would not be very useful as a "safety net". Since even with
```elm
import Dict exposing (Dict)
```
instead of
```elm
import Dict exposing (Dict(..))
```
one wouldn't really have hidden away the constructors. They would still be available in qualified form `Dict.Node` or whatever, instead of just `Node`.

So: "opaqueness" etc. is not the answer to Hassan's question about why *imports* come in the above two flavours.

**Comment by TheSeamau5** [comment]
Yup, it's only about imports. The thing is that I only ever think of union types as types, not as collections or unions of constructors. And, in that light, it feels weird to have to import union types and type aliases.

That said, as an aside, it would be interesting to treat opaque types differently. They have their place and it may be valuable to have a declarative way to say that they're opaque.

For example

```elm
opaque type Html = Html
```

And you can only use that constructor in the same file as the definition of the type. I think this is better than remembering or not to write `(..)` in the module statement. 

Although, this is just an aside and has nothing to do with the main point of this thread which is dealing with type aliases and union types in the import statement.

**Comment by jvoigtlaender** [comment]
Another comment: The earlier remark about this coming from Haskell (and making not much sense) is not really applicable. The situation in Haskell is different since if you write
```haskell
import Dict (Dict)
```
in Haskell, then you *do* completely hide away the constructors (not just their unqualified names). So in Haskell, you can actually make a type opaque on import. The constructor `Dict.Node` will not be available in the importing module, under no name whatsoever, even if the exporting module exports the constructor.

The difference in Elm comes from the fact that an `import` always brings into scope all the definitions from the imported module, albeit in qualified form. That is a new thing that came with Elm 0.15, and I wonder whether in the course of that change it was overlooked that making a difference between importing `Dict` and importing `Dict(..)` ceases to make much sense (because the constructors will be imported *anyway*, just with their qualified name).

Anyway: As said, the situation in Haskell is different, since you *can* actually completely hide constructors (not just their unqualified names) at the import side.

**Comment by TheSeamau5** [comment]
This is exactly why it has started to trip me. The fact that Elm has added the `exposing` keyword brings new expectations. There is an assumption that `exposing` exposes stuff. The idea that you can still hide stuff with `exposing` is weird (by not including the dot-dot). 

Now, with Elm, I'm much more encouraged to use qualified functions and types, even with union type constructors, and I feel fine doing that with the name of the import.

For example

```elm
import MyButton
...

-- somewhere in the code
   case action of 
     MyButton.Click -> ...
     
     MyButton.NoOp -> ...
```

On the other hand, with Haskell, it just feels easier to just import everything and just use `Click` and `NoOp` unqualified.

**Comment by mgold** [comment]
Janis, thank you for pointing that out. Sorry for the confusion.

Okay, on _import_... what if you imported two modules with a `NoOp` tag/constructor? Then the unqualified version would be ambiguous and you'd have to qualify it.

> The idea that you can still hide stuff with `exposing` is weird (by not including the dot-dot).

Correct me if I'm wrong, but each of the following should import a strict superset of unqualified symbols compared the the previous one:

* `import MyButton`
* `import MyButton exposing (Action)`
* `import MyButton exposing (Action(..))`

So you're not really hiding it, you're more not showing it.

**Comment by TheSeamau5** [comment]
> So you're not really hiding it, you're more not showing it.

???
My mind is melting from this statement

> Okay, on import... what if you imported two modules with a NoOp tag/constructor? 

```elm

import MyButton
import MyCheckbox

....

type Action 
  = ButtonAction MyButton.Action 
  | CheckboxAction MyCheckbox.Action


....

update : Action -> State -> State 
update action state = 
  case action of 
    ButtonAction buttonAction -> 
       case buttonAction of 
           MyButton.NoOp -> ...

           ...

    CheckboxAction checkboxAction -> 
       case checkboxAction of 
          MyCheckbox.NoOp -> ...
```

If there are multiple `NoOp` constructors, just qualify them with the module name.

**Comment by jvoigtlaender** [comment]
But I think Max has a point here. Yes, you can always qualify with the module name. You shouldn't be forced to, though. Maybe you do import the `MyButton.Action` and `MyCheckbox.Action` types (actually, let's say that the relevant type in `MyCheckbox` has some other name `OtherType`), but you know you will only ever need to pattern match on `MyButton.Action` values (whereas `MyCheckbox.OtherType` values will only ever be passed around in your module). Then you want to be able to say
```elm
import MyButton exposing (Action (..))
import MyCheckbox exposing (OtherType)
```
to be able to use the constructors of `MyButton.Action` directly.

You could say that one shouldn't be able to do this, that one should even in that situation use the qualified names of `MyButton.Action` constructors. But that would be equivalent to depriving the programmer of the option to use, for example, `List.map` unqualified if the programmer knows that in a given module no other `map` is used. In spirit, the above does what
```elm
import List exposing (map)
import Array
```
does. This will allow the programmer to use `map` to mean `List.map`. (While `Arrow.map` would still be available in case it turns out to be needed.) Saying above that the programmer shouldn't be able to import `MyButton.Action.NoOp` unqualified but `MyCheckbox.OtherType.NoOp` only qualified is like saying here that the programmer shouldn't be able to import `List.map` unqualified but `Array.map` only qualified.

So, all in all, I think that the current Elm situation makes good sense.

**Comment by mgold** [comment]
So I had one more idea, and that is, what if you want an opaque type alias? For example, a hidden record type, but you want people to be able to write their type annotations? Then you might want to do the same thing as a union type, writing `myThing(..)` to expose the implementation and `myThing` to just export the type.

I see that [Forms](https://github.com/elm-lang/core/blob/master/src/Graphics/Collage.elm#L56) are just aliases but you don't see them in type error messages, though that may be at the error reporting level. Oh interesting, you can actually use record updates on forms. And if Evan wanted to change them that would be a major release.

Yeah, I guess this is just a fundamental difference between union types and type aliases. You can't hide aliases because they're made from types the other library already has access to. If you want to hide a record, make it a union with one tag. Which sucks because `{foo, bar}` becomes '(T {foo, bar})` but oh well.

Yeah, I think how it works now makes sense.

**Comment by jvoigtlaender** [comment]
Yes, hiding a record type should be done by putting it into a union type with only one tag.

And yes, it is rather strange that `Form` is not properly encapsulated, but instead is an alias for a record type whose fields are not documented anywhere.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/core/issues/283.

**Comment by evancz** [comment]
I think the problem is that you sometimes do not want all the tags to be available unqualified. So if you say:

```elm
import Either exposing (Either)
```

You are saying you want to be able to mention the `Either` type, but still need to say `Either.Left` and `Either.Right` in the code.
