### ISSUE TITLE
UX of "Error reading build artifact"

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#976]
After upgrading to Elm 0.15.1, I get this:

```
Error reading build artifact elm-stuff/build-artifacts/elm-lang/core/2.1.0/Array.elmi
    The file was generated by a previous build and may be outdated or corrupt.
    Please remove the file and try again.
```

Is there any reason not to structure `elm-stuff` like this?

```
elm-stuff/
  build-artifacts/
    0.15.0/
      NoRedInk/
      elm-lang/
      evancz/
    0.15.1/
      NoRedInk/
      elm-lang/
      evancz/
```

This seems like it would make it so I never had to see this error again. :smile:

**Comment by Apanatshka** [comment]
Or have the tool delete it. The `elm-stuff/build-artifacts` directory is under control of the compiler/build tool. Why ask the user to go into there and delete things the tool generated and usually governs itself?

**Comment by evancz** [comment]
Yeah, lets file this on `elm-make` which is in charge of managing these files. I think both scenarios are plausible solutions. If there is a case where someone wants to be building with two different versions simultaneously, Richard's might be the way to go because the wasted memory is worth it. Let's try to think of such a case in the issue on elm-make!

**Comment by rtfeldman** [comment]
Done: https://github.com/elm-lang/elm-make/issues/30

**Comment by evancz** [comment]
Awesome, thanks!
