### ISSUE TITLE
type inference regression from 0.15 to 0.15.1

### ISSUE THREAD

**Issue by Dobiasd** [elm-lang/elm-compiler#998]
Sure, the following code is incorrect, but it procuded a stack overflow error with [Try Elm](http://elm-lang.org/try) instead of a type error.

    import Graphics.Element

    type alias Foo = {
        a : String
      , b : String
      , c : String
      }

    foos : List Foo
    foos = [
        Foo "" "" ""
      , Foo "" ""
      , Foo ""
      ]

    main = Graphics.Element.spacer 1 1

**Comment by mgold** [comment]
Slightly more minimal reproduction:
```elm
type alias Foo = {
    a : String
  , b : String
  , c : String
  }

foos : List Foo
foos = [
    Foo "" ""
  , Foo ""
  ]
```
The type annotation can be removed and the error still occurs. However, `vals = [ clamp 0 1 , clamp 0 ]` is rejected with a reasonable message.

**Comment by evancz** [comment]
Is this a regression? Is it known if this caused a blow up with 0.15, or is it just 0.15.1?

**Comment by mgold** [comment]
Hadn't thought to test. [Turns out](http://share-elm.com/sprout/55c18a3ae4b06aacf0e8bbd7) it is indeed a regression since 0.15!

**Comment by evancz** [comment]
Interesting, does the error appear the same in the master branch?

If so, is anyone able to do a bisect? I did a search like this for a regression found by @jvoigtlaender in #964. I opened up the commit history for elm-compiler and elm-make so that I could step through them together based on dates. They rely on each other to some extent so they need to be synced up.

**Comment by mgold** [comment]
It still appears to be a problem on master. I suppose it would be possible to bisect between 0.15 and 0.15.1.

**Comment by evancz** [comment]
Been playing around with this. Here's another version of the same thing:

```elm
bar : String -> String -> String -> Int
bar a b c =
  case (a, b, c) of
    ("a", "b", "c") ->
        42

    _ ->
        0

foos =
  [ bar "" ""
  , bar ""
  ]
```

Things work fine if you take off the type annotation. It is also true that the code created by a type alias always has a type annotation, so that's the root cause there.

It seems that the issue is that unification creates an infinite type iff the type signature is given.

**Comment by evancz** [comment]
Alright, this is deregressed in the `type-fixes` branch which I'm in the process of merging into master. I am seeing the correct results for @Dobiasd, @mgold, and my examples.

With @mgold's:

```elm
type alias Foo =
  { a : String
  , b : String
  , c : String
  }

foos : List Foo
foos =
  [ Foo "" ""
  , Foo ""
  ]
```

I am now seeing this error message:

![screen shot 2015-10-22 at 6 42 28 pm](https://cloud.githubusercontent.com/assets/1658058/10682640/07b7b106-78ed-11e5-9e0f-fb6dc0bc891b.png)

**Comment by mgold** [comment]
:+1:
